ada-url/ada

CMakeLists.txt, benchmarks/CMakeLists.txt, benchmarks/bench.cpp
This PR adds several new reference libraries, including curl.
=> This extends the benchmarks.

CMakeLists.txt, README.md
This will make building ada a bit nicer with respect to the ICU dependency.
(It could be improved further.)
=> This makes the ICU requirement less hostile.

benchmarks/bench.cpp, include/ada/checkers.h, include/ada/helpers.h, include/ada/serializers.h, src/checkers.cpp, src/helpers.cpp, src/serializers.cpp, src/unicode.cpp
Before
```
BasicBench_AdaURL            7374 ns         7341 ns        94908 time/byte=9.64605ns
```
After
```
BasicBench_AdaURL            7199 ns         7189 ns        97386 time/byte=9.44628ns
```
=> perf: improve is_ipv4_number_valid

include/ada/helpers.h, include/ada/unicode.h, src/CMakeLists.txt, src/character_sets.cpp, src/helpers.cpp, src/parser.cpp, src/unicode.cpp
Several minor optimizations. Here are the numbers on my laptop (M2, LLVM 14).
Current main branch
```
$ ./buildmain/benchmarks/bench --benchmark_repetitions=1 --benchmark_filter=Ada
BasicBench_AdaURL      13544 ns        13543 ns        51656 time/byte=16.7615ns
```
The PR split-fragment-state by @anonrig 
```
$ ./build-split-fragment-state/benchmarks/bench --benchmark_repetitions=1 --benchmark_filter=Ada 
BasicBench_AdaURL      11132 ns        11131 ns        63155 time/byte=13.7761ns
```
This PR:
```
$ ./build-dlemire-split-fragment-state/benchmarks/bench --benchmark_repetitions=1 --benchmark_filter=Ada 
BasicBench_AdaURL       9136 ns         9135 ns        76940 time/byte=11.306ns
```
Note: This is a PR on split-fragment-state *not the main branch*. Merging this would modify the …
=> A bit faster.

benchmarks/bench.cpp, include/ada/helpers.h, include/ada/parser.h, include/ada/unicode.h, include/ada/url.h, src/helpers.cpp, src/parser.cpp, src/unicode.cpp
Before: `8560ns`
After: `8144ns`
=> perf: remove buffer concat from port state

.github/workflows/ubuntu-sanitized.yml, tests/CMakeLists.txt, tests/basic_fuzzer.cpp
Checking whether we crash easily.
=> Adding basic fuzzer.

src/unicode.cpp
This makes is_double_dot_path_segment quite fast. Basically, we check that the length is 2, 4 or 6 and that the string begins by '.' or '%'. With only these two conditions, we can basically avoid the rest of the processing in almost all cases.
```
This PR:
BasicBench_AdaURL       7727 ns         7727 ns        90425 time/byte=9.56277ns
BasicBench_AdaURL       7754 ns         7753 ns        90129 time/byte=9.59574ns
BasicBench_AdaURL       7844 ns         7843 ns        90574 time/byte=9.70674ns
BasicBench_AdaURL       7733 ns         7733 ns        90590 time/byte=9.57049ns
Main branch:
BasicBench_AdaURL       8178 ns         8178 ns        85829 time/byte=10.1209ns
BasicBench_AdaURL       8006 ns         8006 ns        87165 time/byte=9.90789ns
BasicBench_AdaURL       8017 ns …
```
=> Optimizing the function is_double_dot_path_segment

include/ada/parser.h, include/ada/unicode.h, src/parser.cpp, src/unicode.cpp, src/url.cpp, tests/wpt_tests.cpp
It helps to state what `to_ascii` does more precisely.
Note that setting a parameter to true would resolve https://github.com/ada-url/ada/issues/69
=> Improves the documentation of to_ascii so that we know what it does.

include/ada/implementation.h, include/ada/url.h, src/implementation.cpp, src/parser.cpp, src/url.cpp
This pulls out path parsing from the giant state machine. Performance is better in my tests, but the main motivation is to improve code maintenance and allow further optimizations.
=> Pulled out parse_path as its own function.

include/ada/url.h, src/implementation.cpp, src/parser.cpp, src/url.cpp
Fixes https://github.com/ada-url/ada/issues/74
=> feat: move parse_scheme to its own function

include/ada/helpers.h, include/ada/implementation.h, include/ada/parser.h, include/ada/unicode.h, src/helpers.cpp, src/implementation.cpp, src/parser.cpp, src/unicode.cpp, tests/wpt/toascii.json, tests/wpt_tests.cpp
Fixes https://github.com/ada-url/ada/issues/75 and https://github.com/ada-url/ada/issues/76
=> refactor: remove state_override from set_scheme

src/url.cpp
=> Cleaning the percent optimization.

include/ada/common_defs.h, include/ada/unicode.h, src/CMakeLists.txt, src/helpers.cpp, src/parser.cpp, src/unicode.cpp, src/url.cpp
The function has_tabs_or_newline is vectorizable and it slightly improves the performance.
=> Improving the performance of has_tabs_or_newline

.github/workflows/ubuntu-s390x.yml, CMakeLists.txt, include/ada/common_defs.h
Fixes https://github.com/ada-url/ada/issues/97
=> feat: add is big endian detection

tests/wpt/ada_extra_urltestdata.json, tests/wpt_tests.cpp
The WPT tests were not complete and they are still not complete. I flushed them out a bit more and it reveals issues (potential bugs).
=> Completing the tests and revealing issues.

tests/wpt/ada_extra_setters_tests.json, tests/wpt_tests.cpp
This adds more tests... this time on the encoding.
=> Testing the encoding.

benchmarks/benchmark_template.cpp, benchmarks/performancecounters/apple_arm_events.h, benchmarks/performancecounters/event_counter.h
@anonrig  should check that it works for him. If so, let us merge.
Note that tests *will* fail because we have bugs. This PR does not create new bugs.
Fixes https://github.com/ada-url/ada/issues/92
=> This might fix the issue with Apple counters.

tests/wpt/ada_extra_urltestdata.json
Adds https://github.com/ada-url/ada/issues/146
=> test: add error case

include/ada/url.h, src/url.cpp, tests/wpt_tests.cpp
This PR lets URL strings with bad domains parse, but allows us to check later whether the domain is valid.
=> Add method to check for bad domains.

src/url.cpp
This is just for elegance and maintainability (it looks faster but probably is not).
=> Simplifies the 'parse_host' fast path.

include/ada/parser.h, src/parser.cpp
Fixes https://github.com/ada-url/ada/issues/152
=> refactor: remove optional_url dead code

src/parser.cpp, src/unicode.cpp
We can simplify the code slightly.
=> fix: We had two unnecessary comparisons.

include/ada/url.h, src/implementation.cpp, src/parser.cpp, src/url-setters.cpp, src/url.cpp, tests/wpt/ada_extra_urltestdata.json
Basically, this is a minor PR fixing a few minor issues.
=> fix: We should fail if the base url is invalid. And the setters should return an indication success

CMakeLists.txt, benchmarks/CMakeLists.txt, benchmarks/benchmark_template.cpp, benchmarks/percent_encode.cpp, tests/CMakeLists.txt
It is a bit silly, but if you want to use WPT for performance benchmarks... well you now can.
=> This adds a benchmark that just runs through a WPT file.

CMakeLists.txt, include/ada/common_defs.h, src/unicode.cpp, tests/wpt_tests.cpp
fixes https://github.com/ada-url/ada/issues/117
=> No-ICU fallback.

src/parser.cpp
Alternative to https://github.com/ada-url/ada/pull/177 
Fixes https://github.com/ada-url/ada/issues/171
=> refactor: simpler simpler parse url

tests/wpt/ada_extra_urltestdata.json
Fixes: https://github.com/ada-url/ada/issues/42
=> Files do have null ports.

.github/workflows/benchmark.yml, .gitignore, benchmarks/wpt_bench.cpp
Fixes https://github.com/ada-url/ada/issues/179
=> build: add continious benchmark CI

include/ada/unicode.h, src/unicode.cpp, src/url.cpp, tests/wpt/ada_extra_urltestdata.json
Before... (bbc_bench)
```
----------------------------------------------------------------------------
Benchmark                  Time             CPU   Iterations UserCounters...
----------------------------------------------------------------------------
BasicBench_AdaURL       2872 ns         2872 ns       241453 speed=300.508M/s time/byte=3.3277ns time/url=319.089ns url/s=3.13392M/s
BasicBench_CURL         6501 ns         6501 ns       109582 speed=132.757M/s time/byte=7.53256ns time/url=722.289ns url/s=1.38449M/s
```
After... (bbc_bench)
```
----------------------------------------------------------------------------
Benchmark                  Time             CPU   Iterations UserCounters...
---------------------------------------------------------------------------- …
```
=> On common URLs, this should speed things up a bit in parse_host.

src/parser.cpp
Before:
```
GHz=6.17 cycle/byte=15.2723 cycles/url=1.12182k instructions/byte=69.255 instructions/cycle=4.53468 instructions/ns=27.979 instructions/url=5.08709k ns/url=181.818 speed=295.053M/s time/byte=3.38922ns time/url=248.953ns url/s=4.01681M/s
```
After:
```
GHz=6.298 cycle/byte=15.5891 cycles/url=1.14509k instructions/byte=69.078 instructions/cycle=4.43117 instructions/ns=27.9075 instructions/url=5.07409k ns/url=181.818 speed=299.983M/s time/byte=3.33352ns time/url=244.862ns url/s=4.08393M/s
```
=> refactor: couple of improvements

benchmarks/benchmark_template.cpp
We don't want to confuse anyone.
=> Let us be clear what follows what spec.

CMakeLists.txt, benchmarks/CMakeLists.txt, benchmarks/benchmark_header.h, benchmarks/benchmark_template.cpp, benchmarks/wpt_bench.cpp, cmake/import.cmake
The CMakeLists.txt changes look large but I just moved ICU detection earlier because url_whatwg needs it.
=> Adding the url_whatwg library to some benchmarks.

include/ada/serializers.h, src/serializers.cpp, tests/wpt/ada_extra_setters_tests.json
Nothing specific in performance gain, but added couple of optimization opportunities for ipv6
=> refactor: improve ipv6 serializer

src/url.cpp
This is mostly just cleaning. There is nothing clever about it. I added lots of comments, and made the code much more readable. I have also reorganized it so that it is easier to follow. However, the simplification also saves some instructions here and there.
=> Introducing a simpler and slightly faster 'fast path' for path processing

README.md, benchmarks/benchmark_template.cpp, include/ada/implementation.h
Fixes https://github.com/ada-url/ada/issues/192
=> ault-tolerant benchmarks

src/helpers.cpp, src/unicode.cpp, src/url.cpp, tests/basic_tests.cpp
Fixes https://github.com/ada-url/ada/issues/209
=> fix: always check for forbidden domain code point

include/ada/url.h, src/url-setters.cpp
Have moved the implementation to a private helper within the URL struct, I tried moving it to within helpers but was causing issues since the involves updating fields within the object.
Fixes: https://github.com/ada-url/ada/issues/131
=> feat: simplify impl of set_host and set_hostname

src/parser.cpp, src/url-setters.cpp, tests/basic_tests.cpp, tests/wpt/ada_extra_urltestdata.json
Fixes https://github.com/nodejs/node/issues/46755
=> fix href setter and no_scheme edge case

CMakeLists.txt, doxygen, include/ada/ada_version.h, src/url-setters.cpp, tests/wpt/ada_extra_setters_tests.json
Fixes https://github.com/ada-url/ada/issues/229
=> fix: check and eliminate non ascii on port setter

benchmarks/performancecounters/apple_arm_events.h, benchmarks/performancecounters/event_counter.h
This looks like a large change, but all it does is that we are getting rid of global variables and putting the data into a struct instead. So elementary software engineering.
=> Improving the organization of the code in apple events.

README.md
Added scorecard badge. Related to #235 implementation
=> chore: added OpenSSF Scorecard badge

contribute/issue-template.md
ref: https://github.com/ada-url/ada/issues/199
Hey everyone! Please let me know if this is what is expected for an "issue template".
=> Contribute: adds template for issues

include/ada/url_aggregator-inl.h, include/ada/url_aggregator.h, src/parser.cpp, src/url_aggregator.cpp, tests/wpt_tests.cpp
=> feat: add authority state parsing

.github/workflows/alpine.yml
Let us make sure we don't have hidden dependencies.
=> It should be possible to build and benchmark ada with a minimal linux distribution (alpine)

include/ada/url_aggregator-inl.h, include/ada/url_aggregator.h, src/parser.cpp
=> optimization: reserving memory for url_allocator

.github/workflows/ubuntu-sanitized.yml, include/ada/helpers.h, include/ada/url_aggregator-inl.h, include/ada/url_aggregator.h, src/helpers.cpp, src/parser.cpp, src/url_aggregator.cpp, tests/wpt_tests.cpp
We materialize fewer strings. 
Furthermore, I turn on ADA_DEVELOPMENT_CHECKS explicitly in one of our CI routine (should have no effect because it should already be  ON, but I want to make sure).
=> This adds some optimization to ada::url_aggregator

tools/CMakeLists.txt, tools/adaparse.cpp
Using cxxopts, we improve the usability of the command-line tool.
=> Improving adaparse

include/ada/unicode.h, src/unicode.cpp
This is self explanatory. No, it won't change the performance or any such thing, but it is better to make the intent clear.
=> make contains_forbidden_domain_code_point const values

src/CMakeLists.txt
Fixes https://github.com/ada-url/ada/issues/327
=> Fixing issue 327

include/ada/url-inl.h, include/ada/url.h, include/ada/url_aggregator-inl.h, include/ada/url_aggregator.h, src/url-setters.cpp, src/url.cpp, src/url_aggregator.cpp, tests/url_components.cpp
Fixes https://github.com/ada-url/ada/issues/323
=> refactor: normalize has_credentials method name

benchmarks/CMakeLists.txt, benchmarks/model_bench.cpp, include/ada/url-inl.h, include/ada/url.h, include/ada/url_aggregator-inl.h, include/ada/url_aggregator.h, include/ada/url_base.h
This PR adds a new benchmarking tool. This tool captures performance counters for individual URLs. It only works well under Linux currently.
=> feat: adding a new high-precision benchmarking tool (for Linux only).

.github/workflows/lint_and_format_check.yml
ref: https://github.com/ada-url/ada/issues/349
=> Fix lint_and_format_check.yml not running

include/ada/implementation.h, src/implementation.cpp
Spec added it recently. We might provide an interface as well, since it enables making some optimizations on our side.
I didn't add any tests for now.
=> feat: add `can_parse` method

fuzz/build.sh
There is no need to build the entire library...
=> Fast fuzzing.

README.md, docs/cli.md
Let us redraw the bar charts as ASCII. This should work everywhere all the time.
=> fix issue 393

src/unicode.cpp
Let us not use unitialized buffer.
(This does not affect the performance measurably.)
=> Fix uninitialized buffer

.github/dependabot.yml, .github/workflows/wpt-updater.yml, include/ada/url-inl.h, include/ada/url_aggregator-inl.h, tests/wpt/percent-encoding.json, tests/wpt/urltestdata.json
Fixes https://github.com/ada-url/ada/issues/422
=> test: update web platform tests

include/ada/percent_decoder.h, src/unicode.cpp
Merging to one of our branches for further work.
=> Simd percent decoder

include/ada/ada_idna.h, include/ada/unicode.h, include/ada/url-inl.h, include/ada/url.h, include/ada/url_aggregator-inl.h, include/ada/url_aggregator.h, include/ada/url_base.h, src/helpers.cpp, src/parser.cpp, src/url-getters.cpp, src/url-setters.cpp, src/url.cpp, src/url_aggregator.cpp, tests/CMakeLists.txt, tests/basic_tests.cpp, tests/url_search_params.cpp, tests/wpt_tests.cpp
No big deal, just want to make sure we expose problems later if we change percent/space encoding.
=> 2-3 additional tests.

include/ada/expected.h
Ref: https://github.com/ada-url/rust/pull/23
=> chore: update `expected` to v1.1.0

include/ada_c.h, src/ada_c.cpp, tests/ada_c.cpp
=> refactor: update schema to scheme in c api

README.md
=> doc: improving the WHATWG URL documentation.

README.md
Adding a _quick start_, for people in a rush.
=> Quick start!

README.md
=> link to talk

CMakeLists.txt
Fixes https://github.com/ada-url/ada/issues/596
=> add C++17 requirement directly in CMake

src/CMakeLists.txt
Fixes https://github.com/ada-url/ada/issues/598
=> This makes ada's target compile options private under Windows.

tools/run-clangcldocker.sh
Small changes, nothing noteworthy
=> refactor: update run-clangcldocker.sh

.github/workflows/wpt-updater.yml
WPT script is failing again. Updating due to recent changes to Github
=> fix: update wpt-updater github workflow

.github/workflows/cifuzz.yml
Relates to: https://github.com/ada-url/ada/pull/655
=> Disable memory sanitizer from fuzz workflow

.github/workflows/lint_and_format_check.yml, pyproject.toml, singleheader/amalgamate.py, tools/release/create_release.py, tools/release/lib/release.py, tools/release/lib/tests/test_release.py, tools/release/lib/tests/test_update_versions.py, tools/release/lib/versions.py, tools/release/update_versions.py
Updated Ruff and fixed all linter and formatter errors.
=> fix: modernize python code

README.md, include/ada/parser.h
… just some extra documentation.
=> doc: make sure that it is clear that the strings are assumed to be valid UTF-8.

.github/FUNDING.yml
This adds sponsorship links for @lemire and me.
=> docs: add sponsorship links

include/ada/unicode.h, src/unicode.cpp
Removes unused and private function
=> remove unused private function

include/ada/common_defs.h, include/ada/url_aggregator-inl.h, include/ada/url_aggregator.h, src/url_aggregator.cpp
https://lemire.me/blog/2024/07/26/safer-code-in-c-with-lifetime-bounds/
=> adding some support for lifetime bounds

src/CMakeLists.txt
This extends the range of the sanitizers.
=> chore: extend sanitizers to the library 

include/ada.h, include/ada/helpers.h, include/ada/implementation-inl.h, include/ada/url_pattern.h, include/ada/url_pattern_helpers.h, src/helpers.cpp, src/parser.cpp, src/url_pattern.cpp
=> simpler version of the yagiz/add-url-pattern branch

README.md
New bindings for Ada
TODO: add D bindings in ada-website/doc
cc: @anonrig 
ref.: https://github.com/ada-url/ada/pull/787#issuecomment-2571763437
=> readme: D bindings for Ada

fuzz/url.dict, tests/basic_tests.cpp
Adds a test and an item to fuzzer dictionary
=> extend tests and oss-fuzz

include/ada/implementation.h, include/ada/url_pattern-inl.h, src/url_pattern_regex.cpp, tests/wpt_urlpattern_tests.cpp
This change is required to pass almost all WPT on Node.js
=> update url_pattern to pass more wpt on node.js

include/ada/helpers.h, include/ada/implementation.h, include/ada/parser-inl.h, include/ada/unicode.h, include/ada/url.h, include/ada/url_aggregator-inl.h, include/ada/url_aggregator.h, include/ada/url_base.h, include/ada/url_pattern.h, include/ada/url_pattern_regex.h
One day, C++ will have support for modules, but for now, let us maintain good include practices.
=> adding missing headers

include/ada/url_pattern-inl.h, tests/wpt_urlpattern_tests.cpp
Fixes https://github.com/nodejs/node/issues/57043
=> fix edge case where hash and search is empty

.github/workflows/ubuntu-s390x.yml
Attempt to improve s390x build error ratio
=> use gcc12 on s390x

.github/workflows/wpt-updater.yml, tools/update-wpt.sh
let's split the pull-requests for WPT
=> update wpt-updater to open different prs

include/ada/implementation-inl.h, include/ada/implementation.h, include/ada/parser-inl.h, include/ada/parser.h, include/ada/url_aggregator.h, include/ada/url_pattern.h, include/ada/url_pattern_init.h, src/url_pattern.cpp
Fixes coverity issues. (available thanks to node.js - https://scan9.scan.coverity.com/#/project-view/55652/10075)
=> fix covertiy related issues

tests/wpt/urlpatterntestdata.json
Depends on: https://github.com/web-platform-tests/wpt/pull/51220
cc @annevk @lemire @jasnell
=> apply new urlpattern tests

tests/wpt/toascii.json, tests/wpt/urltestdata.json
Splits https://github.com/ada-url/ada/pull/906 into multiple PRs
=> update toascii.json and urltestdata.json

.github/workflows/ubuntu.yml, tests/wpt/urlpatterntestdata.json, tests/wpt_urlpattern_tests.cpp
Update test runner to skip invalid tests. (Invalid in the sense of they won't succeed with std::regex)
=> update test runner for urlpattern

include/ada.h, include/ada/implementation-inl.h, include/ada/implementation.h, include/ada/parser-inl.h, include/ada/parser.h, include/ada/url_pattern-inl.h, include/ada/url_pattern.h, include/ada/url_pattern_helpers-inl.h, include/ada/url_pattern_helpers.h, include/ada/url_pattern_init.h, include/ada/url_pattern_regex.h, singleheader/CMakeLists.txt
Fixes https://github.com/ada-url/ada/issues/943
=> being more restrictive with the ADA_INCLUDE_URL_PATTERN guards

src/checkers.cpp, tests/basic_tests.cpp
fixes https://github.com/ada-url/ada/issues/970
=> fixing issue 970
