benchmarks/CMakeLists.txt

Merely having boost is *not good enough*. We need a fairly recent Boost.

Actually, we require Boost 1.80 or better.

---

src/parser.cpp

When assigning to uint16_t, doing uint16_t x = uint16_t(a) + uint16_t(b) is maybe not doing what one expects because uint16_t(a) + uint16_t(b) is promoted to int... and then you are left with an implicit cast back to uint16_t.

Fixing anti-pattern related to integer promotion

---

benchmarks/bench.cpp

We definitively do not want to do that !

The benchmarking code was flawed because it was accidentally copying the strings.

---

include/ada/checkers.h
src/checkers.cpp

Before
```
BasicBench_AdaURL           10253 ns        10161 ns        69455 time/byte=13.3522ns
```
After
```
BasicBench_AdaURL            7374 ns         7341 ns        94908 time/byte=9.64605ns
```

perf: improve ends_in_a_number by 25%

---

src/parser.cpp
src/scheme.cpp
src/url.cpp

This should be pretty clear. It is much simpler code. No more std::memcpy or std::unordered_map. It is just straight, clean code. And it should be pretty fast too.

Getting rid of the unordered map.

---

include/ada.h
include/ada/helpers.h
include/ada/unicode.h
src/CMakeLists.txt
src/ada.cpp
src/character_sets.cpp
src/checkers.cpp
src/helpers.cpp
src/parser.cpp
src/unicode.cpp

Before:
```
BasicBench_AdaURL           12170 ns        12165 ns        57778 time/byte=15.0553ns
```
After:
```
BasicBench_AdaURL            7513 ns         7513 ns        93508 time/byte=9.29769ns
```

perf: precalculate fragment and scheme state

---

include/ada/checkers.h
include/ada/helpers.h
include/ada/parser.h
include/ada/unicode.h
src/checkers.cpp
src/helpers.cpp
src/parser.cpp
src/serializers.cpp
src/unicode.cpp
tests/wpt_tests.cpp

This is part of a larger strategy which consists in pulling up some work so that later steps are cheap. Ideally, you'd have an integrated first step which does a bunch of work quickly... identify the location of the first #, check whether it is all ASCII and so forth.
```
GCC12
Linux ip-172-31-33-234 5.15.0-1022-aws #26-Ubuntu SMP Thu Oct 13 12:59:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Main branch:
BasicBench_AdaURL      13879 ns        13800 ns        59962 time/byte=17.0797ns
This PR:
BasicBench_AdaURL       8330 ns         8330 ns        85169 time/byte=10.3091ns
```
Your numbers will vary, especially as the benchmark may vary from one commit to the other, and the 'main branch' is in flux. However, this code is simpler and that alone is a significant gain. We got rid entirely of …

All around optimizations.

---

include/ada/checkers.h
src/checkers.cpp
src/parser.cpp

Before:
```
BasicBench_AdaURL            8234 ns         8233 ns        84999 time/byte=10.1898ns
```
After:
```
BasicBench_AdaURL            8075 ns         8075 ns        86405 time/byte=9.99371ns
```

perf: improve input trimming

---

benchmarks/bench.cpp

Printing the time per url and the number of urls processed per second.

---

include/ada/checkers.h
src/parser.cpp

This is a PR for perf-remove-optional-creation.
Basically, we just need `std::string_view::begins_with` but that's C++20. However, we can roll our own.
Performance...
```
This PR:
BasicBench_AdaURL       5304 ns         5304 ns       131773 time/byte=6.56434ns time/url=482.181ns url/s=2.07391M/s
perf remove optional creation:
BasicBench_AdaURL       5373 ns         5372 ns       129493 time/byte=6.64898ns time/url=488.398ns url/s=2.04751M/s
Main branch:
BasicBench_AdaURL       5805 ns         5804 ns       120171 time/byte=7.18339ns time/url=527.653ns url/s=1.89519M/s
```

perf remove optional creation

---

include/ada/checkers.h
include/ada/implementation.h
include/ada/parser.h
include/ada/unicode.h
include/ada/url.h
src/implementation.cpp
src/parser.cpp
src/unicode.cpp
src/url.cpp
tests/wpt_tests.cpp

improves parsing by around ~0.32ns per byte.
before
```
BasicBench_AdaURL       5097 ns         5093 ns       104205 time/byte=6.20336ns time/url=463.01ns url/s=2.15978M/s
```
after
```
BasicBench_AdaURL       4775 ns         4775 ns       107061 time/byte=5.90992ns time/url=434.11ns url/s=2.30356M/s
```

perf: remove std::optional creation for host parsing

---

include/ada/url.h
src/implementation.cpp
src/url.cpp
tests/wpt_tests.cpp

It is only present if the input string is not special.

Mostly this avoids constructing the 'scheme' string in most cases

---

benchmarks/CMakeLists.txt
benchmarks/benchmark_header.h
benchmarks/benchmark_template.cpp
benchmarks/performancecounters/apple_arm_events.h
benchmarks/performancecounters/event_counter.h
benchmarks/performancecounters/linux-perf-events.h
src/url.cpp

This adds performance counters for Linux and ARM-based apple systems. Privileged access is typically needed to get these counters which typically implies that one needs to run the benchmarks using sudo (e.g., `sudo ./bench`).
An interesting metric is `instructions/byte`. Counting instructions is useful because...
1. It is rock solid. You will notice that on the same system, with the same benchmark, you always get almost the same number of instructions for a given task. The main variation source are branch predictions, but modern processors are very good in this respect so that there is little run-to-run difference.
2. We are neither memory bound (we basically run in cache), nor IO bound, nor multithreaded, and we are not dealing with problems that have much data dependencies (the …

feat: adding perf counters

---

README.md
benchmarks/CMakeLists.txt
include/ada/checkers.h
include/ada/common_defs.h
include/ada/unicode.h
src/checkers.cpp
src/parser.cpp
src/unicode.cpp
tests/CMakeLists.txt

This seeks to make ada more robust with respect to older systems. In particular, older version of ICU can allow some non-ASCII punycode, so we need a careful check.

Supporting older systems.

---

include/ada/checkers.h
src/checkers.cpp
src/url.cpp

The gist of the idea here is to first scan the path and establish a signature (a bitset) and from this bitset, we can then quickly select advantageous fast path that match just the needed features.
We have a trivial path where we know that no processing is needed, then we just copy.
Otherwise, we have a slightly faster path were we know we don't need to do percent encoding. But we still have to worry about the dots.
Finally we have the general case.

Introducing fast paths in path processing.

---

benchmarks/CMakeLists.txt
benchmarks/percent_encode.cpp
include/ada/unicode.h
src/unicode.cpp

Some useful insights: UserInfo percent encode takes 3x slower

perf: add percent_encode benchmarks

---

.github/workflows/ubuntu.yml
.github/workflows/ubuntu_clang.yml
.github/workflows/ubuntu_pedantic.yml

We need more recent boost for boost-url to build, and we should try to have libcurl installed.

---

CMakeLists.txt
include/ada/character_sets.h
include/ada/checkers.h
include/ada/encoding_type.h
include/ada/helpers.h
include/ada/implementation.h
include/ada/parser.h
include/ada/scheme.h
include/ada/state.h
include/ada/unicode.h
include/ada/url.h
singleheader/CMakeLists.txt
singleheader/README.md
singleheader/amalgamate.py
singleheader/demo.cpp
tests/CMakeLists.txt

It builds a 'demo' file. Unfortunately, because we have a dependency on ICU (for example), one then needs to do extra work to link the result with the library.
I accidentally found out that we linked twice against ada when building our test executables.

This will add a singleheader script. 

---

benchmarks/benchmark_template.cpp
include/ada/implementation.h
include/ada/parser.h
src/implementation.cpp
src/parser.cpp
tests/basic_fuzzer.cpp
tests/wpt_tests.cpp

This replaces the user-facing `std::optional<ada::url>` with the more conventional `ada::url` pointer. It saves about 10 instructions per URL, so performance-wise it is not impactful. However, it makes the API "more conventional".

Simplify the API.

---

src/url-getters.cpp
tests/wpt_tests.cpp

The current code does not distinguish between "empty string" and "no value". If that's the desired behaviour, then `std::optional<std::string>` is overengineering. Otherwise, if we think that the empty string is different from having no string, then we need to make changes.

fix: Fix getters get_search() and get_hash()

---

doxygen
include/ada/url.h
src/checkers.cpp
src/url-setters.cpp
tests/wpt/ada_extra_setters_tests.json
tests/wpt_tests.cpp

There's no tests for `href` inside `setter_tests.json` file, even though I added the if else check to wpt_tests in my new pull request. We need to add tests for it.
Fixes https://github.com/ada-url/ada/issues/145
Fixes https://github.com/ada-url/ada/issues/160

feat: add href setter

---

benchmarks/benchmark_header.h
benchmarks/benchmark_template.cpp

It is difficult compare directly different approaches that might solve different problems. This PR is an attempt at 'normalizing' the task. Everyone must populate a standard URL data structure. This should be relatively fair (even though fairness is relative).

fix: normalize (some) of the benchmarks

---

src/serializers.cpp

Before:
```
BasicBench_AdaURL     225401 ns       225387 ns         3102 GHz=3.14456 cycle/byte=29.7942 cycles/url=926.337 instructions/byte=120.381 instructions/cycle=4.04042 instructions/ns=12.7054 instructions/url=3.74279k ns/url=294.584 speed=104.425M/s time/byte=9.57625ns time/url=297.736ns url/s=3.35867M/s
```
After:
```
BasicBench_AdaURL     218966 ns       218942 ns         3200 GHz=3.25426 cycle/byte=29.8658 cycles/url=928.561 instructions/byte=120.501 instructions/cycle=4.03474 instructions/ns=13.1301 instructions/url=3.7465k ns/url=285.337 speed=107.499M/s time/byte=9.30241ns time/url=289.223ns url/s=3.45754M/s```

fix: improve longest sequence finder

---

src/url.cpp

When we encounter 4 decimal values in an IP, then the original string was already normalized, so we can just return it. It is assuredly faster than reserialization and it is common.

We should avoid reserialization if we can cheaply avoid it.

---

README.md
benchmarks/benchmark_template.cpp
benchmarks/wpt_bench.cpp
include/ada/expected.h
include/ada/implementation.h
include/ada/parser.h
singleheader/demo.cpp
src/implementation.cpp
src/url-getters.cpp
src/url-setters.cpp
src/url.cpp
tests/basic_fuzzer.cpp
tests/installation/CMakeLists.txt
tests/wpt_tests.cpp
tools/adaparse.cpp

This is a demo/prototype of how we might use `std::expected` (a C++23 feature) in ada. We use a library because it is not yet supported in mainstream systems (since most compilers do not support C++23 yet).
Fixes https://github.com/ada-url/ada/issues/151
The binary bloat is small (700 extra bytes more or less).
The performance effect is nil on bench:
Before...
```
BasicBench_AdaURL_With_Move       2299 ns         2299 ns       305794 speed=351.47M/s time/byte=2.84519ns time/url=208.992ns url/s=4.78486M/s
```
After:
```
BasicBench_AdaURL_With_Move       2298 ns         2298 ns       305233 speed=351.673M/s time/byte=2.84355ns time/url=208.872ns url/s=4.78763M/s
```
It is all a matter of deciding whether we like the API.
Todo:
Note that the expected code is public domain. So we are good.

Using C++23 expected for returns

---

.github/workflows/benchmark.yml
.github/workflows/ubuntu-sanitized.yml
.github/workflows/ubuntu.yml
.github/workflows/ubuntu_install.yml
.github/workflows/ubuntu_old.yml
.github/workflows/ubuntu_pedantic.yml
.github/workflows/visual_studio.yml
.github/workflows/visual_studio_clang.yml
.gitignore
CMakeLists.txt
docs/RELEASE.md
docs/doxygen/header.html
doxygen
include/ada/ada_version.h

Let's wait until the Node.js pull request is merged to release the v1.0.0
Fixes https://github.com/ada-url/ada/issues/207
Fixes https://github.com/ada-url/ada/issues/142

First version release

---

src/url-setters.cpp
tests/basic_tests.cpp
tests/wpt/ada_extra_setters_tests.json
tests/wpt/ada_extra_urltestdata.json
tests/wpt_tests.cpp

WIP
Web platform tests does not include the tests for `search setter`
[Potentially strip trailing spaces from an opaque path](https://url.spec.whatwg.org/#potentially-strip-trailing-spaces-from-an-opaque-path) with [this](https://webidl.spec.whatwg.org/#this).

test: add code coverage for nodejs

---

src/serializers.cpp

The current ipv6 serializer takes each 16-bit integer and...
1. Writes the hex version using `snprintf` to a local buffer. Though `snprintf` is likely efficient, it is still a function call.
2. We call 'append' to a string... this append must find out the length of what `snprintf` wrote, so that's a possible 'strlen' call. Furthermore, the string must potentially allocate.
By replacing all of it by a single call to `std::to_chars` on a generously allocated string, we avoid multiple function calls. The `std::to_chars` gets inlined (very likely in optimized builds). It should result in faster serialization, saving up to 16 function calls in a tight loop.
This is not nearly "as fast as one can go", but it should be faster.

Optimize the ipv6 serializer

---

include/ada/helpers.h
src/checkers.cpp
src/helpers.cpp
src/parser.cpp
src/url-setters.cpp
tests/basic_fuzzer.cpp
tests/basic_tests.cpp
tests/wpt_tests.cpp

This is an alternative to @miguelteixeiraa 's PR  https://github.com/ada-url/ada/pull/231
Miguel got most of the gains, but I am squeezing a few more and simplifying the code a bit...
Here are the results with the `bench` benchmark on an M2 processor (LLVM 14).
main branch
```
BasicBench_AdaURL_With_Move       2003 ns         2002 ns       350705 GHz=4.30689 cycle/byte=10.2129 cycles/url=750.182 instructions/byte=53.4653 instructions/cycle=5.23509 instructions/ns=22.547 instructions/url=3.92727k ns/url=174.182 speed=403.544M/s time/byte=2.47804ns time/url=182.023ns url/s=5.4938M/s
```
This PR:
```
BasicBench_AdaURL_With_Move       1854 ns         1854 ns       373606 GHz=4.4108 cycle/byte=10.0062 cycles/url=735 instructions/byte=50.5025 instructions/cycle=5.04712 instructions/ns=22.2619 …
```

faster replace find first of with find

---

include/ada/helpers.h
src/helpers.cpp
src/parser.cpp

Thanks to @miguelteixeiraa and @lemire 
Before
```
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                            Time             CPU   Iterations        GHz cycle/byte cycles/url instructions/byte instructions/cycle instructions/ns instructions/url     ns/url      speed  time/byte   time/url      url/s
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
BasicBench_AdaURL_With_Copy       2342 ns         2341 ns …
```

perf: improve authority state performance

---

.github/workflows/benchmark.yml
.github/workflows/ubuntu.yml
benchmarks/CMakeLists.txt

You have to run the benchmarks within the build directory otherwise the servo_url library might not be found, due to rpath is set.
Might help with https://github.com/ada-url/ada/issues/233
(We need to merge to find out!)

Checking that bench can run in CI.

---

src/checkers.cpp
tests/wpt/ada_extra_urltestdata.json

I don't know how this one slipped by.

fix: quotes need to be percent encoded in paths.

---

benchmarks/benchmark_template.cpp

It was useful for a time, but I think we should simplify the benchmark runs.

Simplifying the benchmarks: we don't need 'with copy' 

---

src/helpers.cpp

This is nearly trivial but it helps in the common case where there is '.' in the path but there is neither a single-dot nor a double-dot path segment.
On x64 with GCC 11:
This PR:
```
BasicBench_AdaURL_With_Move       3788 ns         3787 ns       188401 GHz=3.45727 cycle/byte=15.6118 cycles/url=1.497k instructions/byte=32.1333 instructions/cycle=2.05826 instructions/ns=7.11599 instructions/url=3.08122k ns/url=433 speed=227.868M/s time/byte=4.38851ns time/url=420.809ns url/s=2.37637M/s
```
Main:
```
BasicBench_AdaURL_With_Move       5196 ns         5196 ns       132032 GHz=3.43774 cycle/byte=21.1124 cycles/url=2.02444k instructions/byte=42.9038 instructions/cycle=2.03216 instructions/ns=6.98604 instructions/url=4.114k ns/url=588.889 speed=166.103M/s time/byte=6.02035ns time/url=577.285ns …
```

Adding an optimization for dots.

---

include/ada/url-inl.h
include/ada/url_components.h
src/parser.cpp

This is a PR on top of https://github.com/ada-url/ada/pull/250, not the main branch.
Basically, I am proposing to make url_components a lightweight object that is very cheap to instantiate and copy. It would make it suitable for our users.

Some proposed changes to feat: add url_components for start/end 

---

benchmarks/CMakeLists.txt
benchmarks/bbc_bench.cpp
benchmarks/bench.cpp
benchmarks/benchmark_header.h
benchmarks/benchmark_template.cpp
benchmarks/competitors/servo-url/lib.rs
benchmarks/percent_encode.cpp
benchmarks/wpt_bench.cpp

* New benchmark which benefits from the 100k URL dataset. It is named 'benchdata'. 
* I have also fixed curl to make our usage more compliant with the documentation.
* Importantly, the benchmark now prints the count of 'bad' URL. (A small number of URLs are invalid.)

feat: add new data benchmark (100k URLs)

---

benchmarks/CMakeLists.txt
src/url-getters.cpp

Before
```
---------------------------------------------------------------------------------------
Benchmark                             Time             CPU   Iterations UserCounters...
---------------------------------------------------------------------------------------
BasicBench_AdaURL              32524681 ns     32480095 ns           21 GHz=3.22738 cycle/byte=12.0204 cycles/url=1044.08 instructions/byte=48.6195 instructions/cycle=4.04475 instructions/ns=13.054 instructions/url=4.22305k ns/url=323.507 speed=267.49M/s time/byte=3.73846ns time/url=324.72ns url/s=3.07958M/s
BasicBench_AdaURL_just_parse   17782300 ns     17774775 ns           40 GHz=3.22596 cycle/byte=6.52503 cycles/url=566.759 instructions/byte=26.3285 instructions/cycle=4.03501 instructions/ns=13.0168 …
```

 perf: improve href getter performance

---

include/ada/url-inl.h

Before
```
---------------------------------------------------------------------------------------
Benchmark                             Time             CPU   Iterations UserCounters...
---------------------------------------------------------------------------------------
BasicBench_AdaURL              31353288 ns     31351500 ns           22 GHz=3.22746 cycle/byte=11.5328 cycles/url=1001.73 instructions/byte=47.2392 instructions/cycle=4.09608 instructions/ns=13.2199 instructions/url=4.10316k ns/url=310.377 speed=277.119M/s time/byte=3.60856ns time/url=313.437ns url/s=3.19044M/s
BasicBench_AdaURL_just_parse   17773036 ns     17765025 ns           40 GHz=3.22812 cycle/byte=6.50058 cycles/url=564.635 instructions/byte=26.3988 instructions/cycle=4.06099 instructions/ns=13.1094 …
```

perf: improve url components getter

---

include/ada/scheme.h

It looks like @anonrig wants us to access more directly the a type attribute, if so we may want to specify its type precisely.

fix the underlying type of scheme::type

---

Dockerfile
README.md

Addition dev container support can be good feature for developers who don't want to install c++ related build tools.
PS: CTEST did not work without change directory to build.

Add vs code dev container support

---

benchmarks/wpt_bench.cpp
include/ada/url-inl.h
include/ada/url.h
include/ada/url_aggregator-inl.h
include/ada/url_aggregator.h
include/ada/url_base.h
src/implementation.cpp
src/parser.cpp
src/url_base.cpp
tests/basic_fuzzer.cpp
tests/basic_tests.cpp
tests/from_file_tests.cpp
tests/url_components.cpp

The PR https://github.com/ada-url/ada/pull/260 and the branch proposal-aggregator represents an excellent development branch allowing us to build the new url_aggregator support created by @anonrig.
However, up till now, it would not build nor pass our test. I find it difficult to work in such a context (it is a personal take), so what this PR does is fix the build. I have not checked the performance, but I assume that it is on par with our main branch.
This PR does not fix or test the new url_aggregator support, it only makes sure that the existing support for the production of ada::url instances is still operational.
Here are the fixes:
1. For some reason, one call to unicode::to_lower_ascii was deleted. I had to put it back. (???)
2. I had to inline a bunch of function. (Trivial issue.) …

Fix: compilation of proposal-aggregator

---

include/ada/url-inl.h
include/ada/url.h
include/ada/url_aggregator-inl.h
include/ada/url_aggregator.h
src/parser.cpp

1. Using std::string_view parameter is good, but it is not enough to ensure good perf and can actually trip you up and worsen the performance. If the caller creates a string, then and pass this string to a function that takes in a string_view, the string gets converted to a string_view. So far so good. But then, in some cases, we recreate a string from the string_view. This is likely worse that just moving the string. I fixed some of these cases, but not all of them.
2. As much as possible, we want to avoid temporary string creation. So creating a string, and then passing it as a string_view is something we should avoid. Instead, we should pass a string_view, pure and simple. If processing is needed, it should be done on the recipient side.
3. If we need to append a percent-encoded …

Various comments on feat-add-protocol-setters

---

include/ada/helpers.h
include/ada/url.h
include/ada/url_aggregator-inl.h
include/ada/url_aggregator.h
src/helpers.cpp
src/parser.cpp
src/url-setters.cpp
src/url.cpp
src/url_aggregator.cpp

It enables some optimizations. Mostly it can make sure that we just append in the common case, never insert. Inserting in the middle of a string is not going to be cheap compared to an append.
I simplify a bit the code by removing unnecessary (and confusing) bool returns that I added earlier. It is a small thing but it bugged.
I fixed a bug with ipv4, but both ipv4 and ipv6 are likely buggy because after the parsing, we go back and put back the serialized string... effectively doubling the host.
I identified a few additional optimization opportunities. A major issue is that many times we do two appends or two insertions whereas just one would be needed. So if the input string contains '?something', we first locate 'something', and then we append '?' followed by an append of 'something'. …

optimization: This PR moves the insertion of the hash last

---

README.md
tests/basic_tests.cpp
tests/wpt/ada_extra_urltestdata.json
tests/wpt_tests.cpp

@pthier  reported the following 
> This is indeed unsafe and causes OOB reads. E.g. for empty url or #x. This should probably be a check against url.fragment.has_value()?
See https://github.com/ada-url/ada/pull/225#discussion_r1140063705
This PR adds tests for empty URLs and hash-only URL. I do not find out-of-bound reads, but the URLs are invalid. The following... is indeed unsafe...
```C++
auto url = ada::parse("#x");
url->get_scheme();
```
But guarding the access, you find that the URL is not accessed.
```C++
auto url = ada::parse("#x");
if(url) {
url->get_scheme();
}
```
This PR adds some documentation in the README to encourage users to check the validity of the result.
I also make the wpt_tests slightly more robust and user-friendly: we now report a summary of the errors (if any) at …

Testing empty and dash URLs (base-less).

---

src/parser.cpp

I cannot produce the error with an actual test case but it seems possible we could end up with an out-of-bound memory access. But even if this were not the case, this PR will produce nicer-looking code. 
credit: @pthier

fix: preventing potential oob

---

src/checkers.cpp
src/helpers.cpp

This PR will slightly increase the probability that a file-type path avoids the slow path. It also improves code readability.
This improves the performance (check).

path parsing optimization and readability improvement to  parse_prepared_path

---

include/ada/common_defs.h
include/ada/url.h
include/ada/url_aggregator-inl.h
include/ada/url_aggregator.h
include/ada/url_components.h
src/url_aggregator.cpp
src/url_components.cpp

This PR fixes a bug in `clear_base_pathname()` (an obvious one, I think).
It also adds *many* asserts that are enabled when running tests with ADA_DEVELOPMENT_CHECKS.
While doing so, I found that the protocol_end seems to point *after* the ':', so I updated the diagrams.
However, I was not able to complete the validation because it not clear what `host_start` is. I recommend we clear this issue out and then add checks to the validate function so that we can be certain that the code obeys our conventions.
Note that while I did not change it, the `ADA_ASSERT_EQUAL` calls do not need to be guarded: they automatically compile to nothing when ADA_DEVELOPMENT_CHECKS is unset.

Fixes clear path and adds many validate

---

include/ada/url_aggregator-inl.h
include/ada/url_aggregator.h
src/helpers.cpp
src/parser.cpp
src/url_aggregator.cpp

1. adds `has_port`
2. speeds up ada::helpers::substring
3. guard `update_base_username` and `update_base_password`
4. fix silly typo `url.set_host(url.get_host());`.
5. fix `url_aggregator::parse_ipv4` in the case where we have a trailing dot.
6. simplifies `get_password()` and `get_username()`.

Various minor fixes to ada::url_aggregator

---

.github/workflows/ubuntu-sanitized.yml
.github/workflows/ubuntu_old.yml
.github/workflows/ubuntu_pedantic.yml
.github/workflows/visual_studio.yml
.github/workflows/visual_studio_clang.yml
include/ada/url_aggregator-inl.h
include/ada/url_aggregator.h
include/ada/url_base.h
src/parser.cpp
src/url.cpp
src/url_aggregator.cpp

1. Inlining is of great importance for performance. In some instances, we include in the source file functions that ought to be inlined. Short functions that only include little code should almost always be inlined. In other cases we define inline functions in the source files... This is not consistent. A function that is inline should be in the header files. There are several cases where we fail to follow this convention... and I am not sure that I am concerned about it, but when it broke the build under Visual Studio.
2. We don't really need get_buffer(), we already have get_href() which is equivalent.
3. We should favor exposing std::string_view instead of returning a reference to an inner std::string instance to make future work easier: consider that we might want to change the inner …

various simplifications to dev branch

---

README.md
include/ada/common_defs.h
include/ada/url-inl.h
include/ada/url.h
include/ada/url_aggregator-inl.h
include/ada/url_aggregator.h
src/url_aggregator.cpp
tests/basic_tests.cpp
tests/wpt_tests.cpp

This PR attempts to add a deliberate "/." between the end of the host and the start of the path when there is no host and when the path has more than 1 character.
It is only a sketch and I wasn't entirely careful... but it seems to be the right idea.
It breaks some our tests but I expect that a few extra fixes should settle it.
This PR is mostly for discussion.
```
Mismatch: 'file:///./C:/foo/bar' - 'file:///C:/foo/bar'
FAIL: href {
"input": "/C|\\foo\\bar",
"base": "file:///tmp/mock/path",
"href": "file:///C:/foo/bar",
"protocol": "file:",
"username": "",
"password": "",
"host": "",
"hostname": "",
"port": "",
"pathname": "/C:/foo/bar",
"search": "",
"hash": ""
}{
"buffer":"file:///./C:/foo/bar",
"protocol":"file:",
"host":"",
"path":"/C:/foo/bar",
"opaque path":false,
"protocol_end":5, …
```

empty host slash dot

---

include/ada/url_aggregator-inl.h
include/ada/url_aggregator.h
src/parser.cpp
src/url_aggregator.cpp
tests/wpt_tests.cpp

Running: `sudo build/benchmarks/bench ./datasets/wikipedia/wikipedia_100k.txt`
Before
```
BasicBench_AdaURL_aggregator              21961383 ns     21959687 ns           32 GHz=3.21847 cycle/byte=13.6115 cycles/url=695.45 instructions/byte=62.6634 instructions/cycle=4.6037 instructions/ns=14.8169 instructions/url=3.20164k ns/url=216.081 speed=232.666M/s time/byte=4.29801ns time/url=219.597ns url/s=4.5538M/s
BasicBench_AdaURL_aggregator_just_parse   22256599 ns     22252937 ns           32 GHz=3.22738 cycle/byte=13.73 cycles/url=701.5 instructions/byte=63.6907 instructions/cycle=4.63881 instructions/ns=14.9712 instructions/url=3.25412k ns/url=217.359 speed=229.6M/s time/byte=4.35541ns time/url=222.529ns url/s=4.49379M/s
```
After
``` …
```

perf: add multiple optimizations

---

include/ada/common_defs.h
include/ada/url-inl.h
include/ada/url.h
include/ada/url_aggregator-inl.h
include/ada/url_aggregator.h
src/parser.cpp
src/url_aggregator.cpp

The main trick that this is using is that instead of, for example, passing the view "http" and then later creating the temporary "http:" which gets added to our buffer, we just pass straight up  "http:" and avoid the messy business entirely. Also, I created new methods to set the URL to file type, very fast (instead of passing the unnecessary string "file").
Apple M2, LLVM 14, benchdata.
Before:
```
Benchmark                                        Time             CPU   Iterations        GHz cycle/byte cycles/url instructions/byte instructions/cycle instructions/ns instructions/url     ns/url      speed  time/byte   time/url      url/s
------------------------------------------------------------------------------------------------------------------------------------------------------------ …
```

Various scheme-related optimizations.

---

include/ada/url_aggregator-inl.h
include/ada/url_aggregator.h

Before
```
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                        Time             CPU   Iterations        GHz cycle/byte cycles/url instructions/byte instructions/cycle instructions/ns instructions/url     ns/url      speed  time/byte   time/url      url/s
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
BasicBench_AdaURL                             3091 ns …
```

feat: add url_aggregator::replace_and_resize

---

include/ada/unicode-inl.h
include/ada/unicode.h
include/ada/url_aggregator-inl.h
include/ada/url_aggregator.h
src/unicode.cpp
src/url_aggregator.cpp
tests/wpt_tests.cpp

It is not expect to impact the performance much because we still end up creating temporary strings. To get rid of them in more significant numbers, we would need push the encoding further and write directly on the buffer. This PR moves us slightly closer to this goal.
This PR also...
1. adds clear_base_hash() (because we can clear everything else!!!)
2. fix the ugly formatting in wpt_tests

This PR reduces the number of some temporary strings.

---

CMakeLists.txt

So we should not try to build the benchmarks under 32-bit systems.

We use Google Benchmark, but it does not build under several 32-bit systems.

---

include/ada/unicode.h
src/unicode.cpp
src/url_aggregator.cpp

Currently, ada::url_aggregator will always copy the domain string to a temporary `std::string` which is the processed and finally copied on our buffer. This processing turns out to have an overhead of nearly 10% in some realistic cases.
This PR optimizes the case when the input domain is all lowercase, which is the common case. We could get smarter, but it seems to be good enough.
Using `benchdata` which defaults on @anonrig 's large URL file.
Before
```
BasicBench_AdaURL_aggregator_href             2394 ns         2390 ns       293043 speed=338.136M/s time/byte=2.95739ns time/url=217.234ns url/s=4.60334M/s
```
After
```
BasicBench_AdaURL_aggregator_href             2184 ns         2180 ns       315622 speed=370.673M/s time/byte=2.69779ns time/url=198.165ns url/s=5.0463M/s
```
So a 10% …

Optimize domain processing.

---

include/ada/helpers.h
include/ada/url-inl.h
include/ada/url.h
include/ada/url_aggregator-inl.h
include/ada/url_aggregator.h
include/ada/url_base.h
src/helpers.cpp
src/parser.cpp
src/url-getters.cpp
src/url-setters.cpp
src/url.cpp
src/url_aggregator.cpp
tests/url_components.cpp

Fixes https://github.com/ada-url/ada/issues/322
Contains a breaking change where `fragment` is renamed to `hash`. We were using `fragment` in `ada::url` but `hash` in `url::aggregator`, even though the functions to set it was `set_hash`.

refactor base prefix and rename fragment to hash

---

include/ada/helpers.h
src/helpers.cpp

Alternative to https://github.com/ada-url/ada/pull/331
credit to @codebytere

fix: bad usage of std::string_view::npos

---

.github/workflows/ubuntu-release.yml
tools/CMakeLists.txt

When `BUILD_TESTING` flag is disabled, build crashes at the moment. This is due to the missing `import.cmake` statement inside `tools` folder. 
An example error from the homebrew pull request:
Ref: https://github.com/Homebrew/homebrew-core/actions/runs/4737212538/jobs/8409814274?pr=128710
Logs
```
==> cmake -B build -DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/ada/2.1.0 -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for …
```

build: add missing import.cmake

---

benchmarks/CMakeLists.txt

At least one competitor requires ICU. If we don't look for ICU, this competitor never gets built and so it never gets benchmarked.

fix: look for ICU.

---

src/ada_idna.cpp
src/helpers.cpp
src/unicode.cpp

In these instances, the uint8_t inputs multiplied with the literal, which is a signed long, will make a signed long. For certain inputs, this will overflow, despite the return type being unsigned. Fix by making it always unsigned in the first place.
I found this because a user in my distribution (which builds all prod packages with a subset of ubsan by default) reported crashes newly introduced in newest nodejs, which apparently brings ada as a dependency. While the branch used by nodejs appears to be different, just putting this here anyway.

fix: ubsan signed overflow violations

---

include/ada/ada_idna.h
src/ada_idna.cpp
src/unicode.cpp

The key elements is that IDNA no longer check for forbidden characters, so an additional check must be added in unicode.cpp. This PR makes to_ascii more lenient.

This bumps IDNA with a recent fix to to_ascii.

---

CMakeLists.txt

Under Visual Studio for ARM64, old versions of the the simdjson library fail to detect NEON and are effectively broken under ARM64. This only affects Visual Studio for ARM64 but it is best fixed.

Bump the simdjson version number.

---

src/parser.cpp
tests/basic_tests.cpp

We potentially reserve string capacity based on the string input size. When the string is empty, there was a potential for us to reserve an undefined amount of memory. This did not happen on current systems but could theoretically happen.
The simple fix is to OR the string size with '1' so that the string size is at least 1, always, and never zero.

fix: better guard empty string inputs

---

README.md
benchmarks/benchmark_template.cpp

Mostly, this PR removes two useless benchmarks, and it adds a short new section to the README to say that ada is fast.

Doc our perf

---

src/url_aggregator.cpp
tests/basic_tests.cpp

This fixes a bug whereas get_host() and get_hostname() get in trouble… when there is no host and they try to nevertheless compute one. We get a string_view with a negative size.:wq

fix bug with get_host() and get_hostname() when there is no host

---

fuzz/parse.cc

Functions such as punycode encoding/decoding are intrinsically expensive. If your input is 200kB, you might end up having to generate 1 MB of output.

We must limit the input sizes in the fuzzer otherwise we might face time-outs

---

tools/release/lib/release.py
tools/release/lib/tests/test_release.py

example:
"some fixes to the C API" in the releease [v2.4.0](https://github.com/ada-url/ada/releases/tag/v2.4.0) that merges [dlemire/fix_c](https://github.com/ada-url/ada/tree/dlemire/fix_c) into  [add-c-api](https://github.com/ada-url/ada/tree/add-c-api) (not merge into the main branch so shouldn't be listed directly in the release notes)

fix: update release script to consider only PRs with base.ref "main"

---

include/ada/common_defs.h
include/ada/unicode.h
src/unicode.cpp

This PR provides SSE2 (x64) and NEON (arm) optimization for *one* function (has_tabs_newlines).
It saves about one instruction per input byte:
`benchdata` results, this PR, GCC11 x64 (Skylake)
```
BasicBench_AdaURL_href              35821587 ns     35778820 ns           18 GHz=3.18736 cycle/byte=13.1335 cycles/url=1.14076k instructions/byte=36.9871 instructions/cycle=2.81625 instructions/ns=8.97639 instructions/url=3.21267k ns/url=357.902 speed=242.828M/s time/byte=4.11814ns time/url=357.699ns url/s=2.79565M/s
BasicBench_AdaURL_aggregator_href   23950378 ns     23922856 ns           29 GHz=3.18859 cycle/byte=8.77344 cycles/url=762.054 instructions/byte=26.0415 instructions/cycle=2.96821 instructions/ns=9.46443 instructions/url=2.26194k ns/url=238.994 speed=363.171M/s time/byte=2.75352ns …
```

One simple SIMD optimization

---

.github/workflows/emscripten.yml
CMakeLists.txt
src/helpers.cpp
src/parser.cpp
tests-wasm/CMakeLists.txt
tests-wasm/test.js.in
tests-wasm/wasm.cpp

This is closely related to https://github.com/ada-url/ada/pull/411 but I am trying to keep everything as automated as possible.
You can build and test as follows:
```
emcmake  cmake -B buildwasm
cmake --build buildwasm
ctest --test-dir buildwasm
```
It is essentially a derivative of the work @MoLow did and he should get most of the credit. I just automated the process.

emscripten support

---

.github/workflows/emscripten.yml
CMakeLists.txt
cmake/ada-flags.cmake

This patch adds a new `ADA_TOOLS` option to allow users enable/disable the build of ada cli tools (`adaparse`) manually.
When trying to add a new port for `ada-url` in `vcpkg`, I found it failed to build `adaparse` on UWP: https://github.com/microsoft/vcpkg/pull/31485 .
`adaparse` uses `fmt::output_file` defined in `fmt/os.h`. However, since UWP doesn't provide _pipe, `FMT_USE_FCNTL` is defined as 0, which in turn means `fmt::output_file` does not exist.
https://github.com/fmtlib/fmt/blob/master/include/fmt/os.h#L23

chore: add ADA_TOOLS option

---

include/ada/unicode.h
src/unicode.cpp
src/url_aggregator.cpp

We had an accidental casting of a byte value to a bool which was disabling an optimization in our code. It turns out that this 'fast' path was never used.
Removing it does not measurably affect the performance and it removes lines of code we can do without.
This routine could be revisited later for more optimizations.
Current main branch on benchdata (Apple M1, LLVM 14):
```
BasicBench_AdaURL_aggregator_href   16168863 ns     16168814 ns           43 GHz=3.4071 cycle/byte=6.30681 cycles/url=547.804 instructions/byte=28.5425 instructions/cycle=4.52566 instructions/ns=15.4194 instructions/url=2.47918k ns/url=160.783 speed=537.336M/s time/byte=1.86103ns time/url=161.648ns url/s=6.18629M/s
```
With this PR
```
BasicBench_AdaURL_aggregator_href   15900795 ns     15900750 ns           44 …
```

Removing optimization that never got used

---

benchmarks/benchmark_template.cpp
benchmarks/performancecounters/apple_arm_events.h
include/ada/checkers-inl.h
include/ada/common_defs.h
include/ada/expected.h
include/ada/unicode.h
include/ada/url.h
include/ada/url_aggregator-inl.h
include/ada/url_aggregator.h
src/ada_idna.cpp
src/helpers.cpp

Some misspellings are detected by using [codespell](https://github.com/codespell-project/codespell) with the following command line:
```bash
$ codespell -L crate,unexpect,OT --skip "*.json"
```

docs: fix typos in code comment

---

src/unicode.cpp

Actually unaligned load is not being so slow on recent CPU, but it should be used when it can be.

Use Aligned Load

---

src/unicode.cpp

this lambda is declared to perform the same operation twice within a local scope.
instead i thought it could be managed as a single function.
it can only be moved into an `internal` namespace, but i'm unsure of the appropriate place for it.

remove duplicate lambda

---

README.md

Added OpenSSF Badge ([![OpenSSF Scorecard](https://api.securityscorecards.dev/projects/github.com/ada-url/ada/badge)](https://securityscorecards.dev/viewer/?uri=github.com/ada-url/ada)) to `README.md`
- de56da94b2228b76a1e48d9fde754efb83c7493a docs: added OpenSSF Scorecard badge by @UlisesGascon

Added OpenSSF Scorecard badge

---

.github/workflows/dependency-review.yml

Added Dependency Review Action
This Action will scan dependency manifest files that change as part of a Pull Request, surfacing known-vulnerable versions of the packages declared or updated in the PR.
Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable packages will be blocked from merging.
[Source repository](https://github.com/actions/dependency-review-action)
- 0e1f1fa chore: added Dependency Review Action by @UlisesGascon

Added Dependency Review Action

---

.github/workflows/cifuzz.yml
.github/workflows/emscripten.yml

Pinned missing Github Actions dependencies
[Full Report](https://kooltheba.github.io/openssf-scorecard-api-visualizer/#/projects/github.com/ada-url/ada/commit/0c67ed538d1ef4a813086820abc0f43ab2e9b732)
- 159ba96 chore: pinned Github Actions dependencies by @UlisesGascon

Pinned Github Actions dependencies

---

.github/dependabot.yml

Extended Dependabot config for Docker, Cargo and Pip
- eae406c chore: added support for docker in dependabot by @UlisesGascon
- 80ef5c5 chore: added support for Cargo in dependabot by @UlisesGascon
- 3e5d1f1 chore: added support for pip in dependabot by @UlisesGascon

Update Dependabot rules

---

.github/workflows/documentation.yml
.github/workflows/wpt-updater.yml

Implementing best practices related to OpenSSF Scorecard.
> The `GITHUB_TOKEN` is an automatically generated secret to make authenticated calls to the GitHub API
If the token is compromised, it can be abused to compromise your environment (e.g., to overwrite releases or source code). This compromise will also impact everyone using your software in their supply chain. [Ref]( https://github.com/step-security/secure-repo#1-automatically-set-minimum-github_token-permissions)
**Additional info**
- [Step Security: Automatically set minimum GITHUB_TOKEN permissions](https://github.com/step-security/secure-repo#1-automatically-set-minimum-github_token-permissions)
- [GitHub Actions: Control permissions for GITHUB_TOKEN](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-fo …

Restrict permissions for GITHUB_TOKEN usage in pipelines

---

fuzz/parse.cc
include/ada/url_search_params-inl.h
include/ada/url_search_params.h
tests/url_search_params.cpp

According to https://url.spec.whatwg.org/#dom-urlsearchparams-has, we need to provide a `has` function that takes two arguments `name` and `value`.

feat: Implement url_search_params::has(name, value)

---

src/parser.cpp

The `state` is assigned inside the next state, and since `[[fallthrough]]` is used, we don't need to assign it.

fix: remove unnecessary state assignment

---

include/ada/checkers-inl.h

This has a slightly better codgen - https://godbolt.org/z/z3onK91bT and supports [execution policy](https://en.cppreference.com/w/cpp/algorithm/execution_policy_tag_t) in case sequential comparisons are not sufficient.

Use std::equal instead of string_view == in begins_with.

---

include/ada/url_base.h
include/ada_c.h
src/ada_c.cpp
src/url.cpp
src/url_aggregator.cpp
tests/ada_c.cpp
tests/basic_tests.cpp

This is one of the missing features comparing `ada-url` rust crate with `url` crate. Original implementation of `url` crate is available at: https://docs.rs/url/2.4.0/url/enum.Host.html

feat: add url host type attribute

---

include/ada_c.h
src/ada_c.cpp
tests/ada_c.cpp

Thanks to @steveklabnik, Ada rust crate can have safe & correct cloning.
Co-authored-by: Steve Klabnik

feat: add `ada_copy` c function

---

fuzz/parse.cc
include/ada/url_aggregator-inl.h
include/ada/url_aggregator.h
include/ada_c.h
src/ada_c.cpp
tests/ada_c.cpp

These methods are required for the Rust crate and is useful for others as well.

feat: add ada_clear_* methods to c api

---

src/unicode.cpp

In case `result` is not created using a subset of the `input` `result.reserve(input.size())` would result in increasing `result`'s size with likely reallocation.
It's similar to https://github.com/ada-url/ada/pull/484

Avoid potentially unnecessary string reallocs.

---

fuzz/parse.cc
include/ada/url_aggregator.h
include/ada_c.h
src/ada_c.cpp
tests/ada_c.cpp

This pull request removes `ada_clear_pathname` because it is not feasible to make this public.
Fixes https://github.com/ada-url/ada/issues/490

Update C api

---

include/ada/unicode.h
src/unicode.cpp

This is an alternative to https://github.com/ada-url/ada/pull/473
Using [the search-params benchmark](https://github.com/ada-url/ada/pull/477), we can use `benchmarks/bench_search_params` to test the speed at which we can parse search parameters. This task is percent-decoding intensive.
GCC 11, Ice Lake processor.
Main:
```
-----------------------------------------------------------------------------------
Benchmark                         Time             CPU   Iterations UserCounters...
-----------------------------------------------------------------------------------
url_search_params_AdaURL      65900 ns        65735 ns        10671 GHz=3.19635 cycle/byte=11.6984 cycles/url=32.773k instructions/byte=40.3667 instructions/cycle=3.45062 instructions/ns=11.0294 instructions/url=113.087k …
```

using a table-based convert_hex_to_binary function for better speed

---

include/ada_c.h
src/ada_c.cpp
tests/ada_c.cpp

This PR adds a new method to retrieve the schema type. This is needed for https://github.com/ada-url/rust/issues/51.

feat: add ada_get_schema_type

---

include/ada/url_aggregator-inl.h
src/url-setters.cpp
src/url_aggregator.cpp
tests/basic_tests.cpp

Passing `set_host("::")` produces invalid URL. Therefore, it is causing Node.js to fail on the next setter.
PS: Safari doesn't have this bug.
```
{
const url = new URL('http://foo')
url.host = '::' // does *not* crash
url.port = 3000 // crashes with the described error below
}
```
Ref: https://github.com/nodejs/node/issues/49650

test: reproduce node.js bug

---

include/ada/checkers-inl.h
include/ada/checkers.h

std::equal is not necessarily constexpr in C++17, so PR  https://github.com/ada-url/ada/pull/474 broke ada technically.
I am removing the constexpr qualifier for now.
See https://en.cppreference.com/w/cpp/algorithm/equal

std::equal is not necessarily constexpr in C++17

---

benchmarks/CMakeLists.txt
src/unicode.cpp

Fix an intermittent issue identified by @isaacs in https://github.com/nodejs/node/issues/49960
I also add `quiet` to the `find_package(ZURI)` request since most people will not have `ZURI` installed on their machine.
I am using `benchdata` to assess the performance impact.
There is a tiny performance impact (Apple M2, LLVM 14) of about 1%. It is small enough to be ignored (likely to go away or flip in another direction if you change compiler or processor).
Main branch:
```
BasicBench_AdaURL_href              24232194 ns     24232103 ns           29 GHz=3.433 cycle/byte=9.31199 cycles/url=808.832 instructions/byte=39.6644 instructions/cycle=4.2595 instructions/ns=14.6229 instructions/url=3.44522k ns/url=235.605 speed=358.536M/s time/byte=2.78912ns time/url=242.26ns url/s=4.12779M/s …
```

fix node issue 49960

---

include/ada/ada_idna.h
include/ada/character_sets-inl.h
include/ada/character_sets.h
include/ada/helpers.h
include/ada/scheme-inl.h
include/ada/serializers.h
include/ada/unicode.h
include/ada/url-inl.h
include/ada/url.h
include/ada/url_aggregator-inl.h
include/ada/url_aggregator.h
include/ada/url_base.h
include/ada/url_components.h
src/url-getters.cpp
src/url.cpp
src/url_aggregator.cpp
src/url_components.cpp

- const-qualified in the function declaration; const-qualification of parameters only has an effect in function definitions
- Some `[[nodiscard]]`s added
- default argument for `parse_port` which is a virtual function is not recommended, I changed it to two different functions
- using `<cstdint>` instead of `<stdint.h>`
- Adding `override` for virtual destructors
- Small changes like comment mismatch fixes and useless "return" statement removal

Warning fixes

---

README.md
fuzz/parse.cc
include/ada/url_search_params-inl.h
include/ada/url_search_params.h
include/ada_c.h
src/ada_c.cpp
tests/ada_c.cpp
tests/url_search_params.cpp

Does two things:
* Adds simple iterators to ada::url_search_params. These are implemented as distinct types with `next()` and `is_done()` methods as opposed to traditional c++ iterators.
* Adds url search params apis to ada_c

Add iterator support to url_search_params

---

singleheader/CMakeLists.txt

We should not use a generic name like `singleheader-files` as it can cause conflicts with other projects.

This adds the prefix ada to a custom target to avoid conflicts.

---

include/ada/url_search_params.h

I do not think that these const qualifiers are useful because the auto is going to be be const, as far as I can tell from my reading of the specification.

Removing const in const auto (return value) in url_search_params.h

---

benchmarks/CMakeLists.txt
benchmarks/benchmark_header.h
benchmarks/benchmark_template.cpp
benchmarks/wpt_bench.cpp

```
--------------------------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations UserCounters...
--------------------------------------------------------------------------------------------
BasicBench_AdaURL_href              25454488 ns     25454481 ns           27 GHz=3.22868 cycle/byte=9.54974 cycles/url=829.483 instructions/byte=40.5726 instructions/cycle=4.24855 instructions/ns=13.7172 instructions/url=3.5241k ns/url=256.911 speed=341.319M/s time/byte=2.92981ns time/url=254.481ns url/s=3.92956M/s
BasicBench_AdaURL_aggregator_href   17160945 ns     17160122 ns           41 GHz=3.2277 cycle/byte=6.34475 cycles/url=551.1 instructions/byte=28.6196 instructions/cycle=4.51076 …
```

perf: update whatwg_url package to latest commit

---

include/ada/url_aggregator-inl.h
tests/basic_tests.cpp

Fixes https://github.com/nodejs/node/issues/50235

verifies and fixes issue 50235 in node.

---

include/ada/url_base.h

As per the C++ specification, there is nothing preventing us from declaring a pure virtual function 'inline'. Nevertheless, some compilers, by static analysis, flags this with a warning. Furthermore, some people turn warnings into errors. And so you go from code that is legal, down to an error.
Note that there probably is no sense in this library to have the virtual function inline, so I am not defending the code as it appeared. It just seems that it was harmless as is.
Fixes https://github.com/ada-url/ada/issues/544

Removing unnecessary inline qualify to pure virtual function

---

include/ada/helpers.h
src/helpers.cpp

We vectorize manually for SSE2 and NEON two functions that relied on SWAR: `find_next_host_delimiter` and `find_next_host_delimiter_special`. To assess the performance effect, we use `benchdata` and the `BasicBench_AdaURL_aggregator_href` measure.
Before: speed=484.976M/
After: speed=496.554M/s
Before: speed=375.019M/s
After: speed=401.595M/s
If we remove optimizations and switch back to the following (which compiles to a bitset lookup, character-by-character), our speed goes down slightly to 372.901M/s (GCC 12, Intel Ice Lake).
```C++
for (size_t i = location; i < view.size(); i++) {
if (view[i] == ':' || view[i] == '/' || view[i] == '\\' ||
view[i] == '?' || view[i] == '[') {
return i;
}
}
return size_t(view.size());
}
```
This might compile to...
```asm
movabs  rcx, 17592186112001
mov …
```

Vectorization of find_next_host_delimiter and find_next_host_delimiter_special

---

CMakeLists.txt
singleheader/CMakeLists.txt

When using ada as a library and embedding it in our project via
FetchContent, we've run into errors like this:
```
[253/1413] Generating ada.cpp, ada.h, ada_c.h, demo.cpp, demo.c, README.md
fatal: detected dubious ownership in repository at '/src/redpanda'
```
In our CI environment we've seen flaky HTTP issues as well:
```
CMake Error at build/_deps/ada-src/cmake/CPM.cmake:19 (file):
file DOWNLOAD cannot compute hash on failed download
status: [22;"HTTP response code said error"]
Call Stack (most recent call first):
build/_deps/ada-src/CMakeLists.txt:27 (include)
CMake Error at build/_deps/ada-src/CMakeLists.txt:32 (CPMAddPackage):
Unknown CMake command "CPMAddPackage".
```
Actually building just the library seems very simple and uses vanilla
cmake. CPM is only used for …

cmake: support disabling CPM

---

.github/workflows/visual_studio.yml
include/ada/checkers.h
src/checkers.cpp

This PR optimizes the is_ipv4 function by first checking the last character. Unless the last character is a hex number or the letter x, we can just return false immediately and save quite a bit of work.
The function was also rewritten with more safeguards.
LLVM 14, Apple M2.
Before:
```
BasicBench_AdaURL_href              24053490 ns     24053414 ns           29 GHz=3.38364 cycle/byte=9.37729 cycles/url=814.504 instructions/byte=38.9054 instructions/cycle=4.14889 instructions/ns=14.0383 instructions/url=3.37929k ns/url=240.719 speed=361.2M/s time/byte=2.76855ns time/url=240.474ns url/s=4.15845M/s
BasicBench_AdaURL_aggregator_href   16111354 ns     16111372 ns           43 GHz=3.48936 cycle/byte=6.19904 cycles/url=538.444 instructions/byte=27.773 instructions/cycle=4.48021 …
```

optimizing is_ipv4

---

.github/workflows/lint_and_format_check.yml
.github/workflows/visual_studio.yml
src/checkers.cpp
src/helpers.cpp
src/unicode.cpp

Instead of having hard-coded tables, we can ask the C++ to generate them.
There is no obvious performance degradation (benchdata, LLVM 14).
cc @ShogunPanda

have the C++ compiler generate the tables.

---

.github/workflows/lint_and_format_check.yml
src/helpers.cpp

Under ARM, we'd like to just do...
```C++
uint8x16_t bit_mask = {0x01, 0x02, 0x4, 0x8, 0x10, 0x20, 0x40, 0x80,
0x01, 0x02, 0x4, 0x8, 0x10, 0x20, 0x40, 0x80};
```
But Visual Studio refuses to let us do it, so we need a workaround. This is a pretty decent one (performance-wise).

Visual Studio ARM workaround

---

src/url.cpp
src/url_aggregator.cpp
tests/basic_tests.cpp

Fix an intermittent issue identified by @danfuzz in https://github.com/nodejs/node/issues/51514
```c++
#include "ada.cpp"
#include "ada.h"
#include <iostream>
int main(int, char *[]) {
auto url = ada::parse<ada::url>("https://1.1.1.256");
if (!url) {
std::cout << "failure" << std::endl;
return EXIT_FAILURE;
}
url->set_protocol("http");
std::cout << url->get_protocol() << std::endl;
std::cout << url->get_host() << std::endl;
return EXIT_SUCCESS;
}
```
Raise an error and stop parse.
Successfully parsed.
This is an edge case, `segment_result` should not be equal to the size of remaining bits.
https://github.com/ada-url/ada/blob/4814d2f62f8c0c4545c39bcbaad3451eceda2ab3/src/url.cpp#L64-L83

Fix check segment_result range(for node issue #51514)

---

include/ada/url_aggregator.h
src/url.cpp
src/url_aggregator.cpp
tests/basic_tests.cpp

When a host is IPv4 but it contains ignorable unicode characters, then `url_aggregator` (but not `url`) gets confused and does not update the host. We therefore end up with an empty host.
See https://github.com/nodejs/node/issues/51593

fix node issue 51593

---

benchmarks/performancecounters/apple_arm_events.h
benchmarks/performancecounters/event_counter.h

In the future, benchmarks should track branch misses. This PR lays the foundation for this upgrade.

exposing branch misses under macos

---

include/ada/character_sets-inl.h
include/ada/character_sets.h
include/ada/checkers.h
include/ada/helpers.h
include/ada/unicode-inl.h
include/ada/unicode.h

We don't want users to rely on internal functions which we could remove or change at any time.
As remarked by @feltech, these internal functions can be helpful in implementing some missing features of general interest in ada. However, we do not want that: we want users to contribute back to the project the missing features in question.
Ideally, we would move these functions off our public header files entirely. It is not difficult to do but it might require a few hours of refactoring and testing. Marking them as private is an easy first step.
Fixes https://github.com/ada-url/ada/issues/580

Marks as private several functions in our header files.

---

include/ada/url-inl.h

This improves readability.
credit @the-moisrex

replace .size() == 0 with empty()

---

benchmarks/benchmark_header.h
benchmarks/model_bench.cpp
include/ada/url_aggregator-inl.h
src/ada_c.cpp
src/url.cpp
src/url_aggregator.cpp
tests/wpt_tests.cpp

Patterns such as
```
auto out = std::string();
```
Are probably best avoided and replaced with...
```
std::string out;
```
This PR makes a few such changes.

simplifies some verbose lines of code.

---

include/ada/scheme-inl.h

As remarked by @the-moisrex in issue 617, [Premature optimiztion](https://github.com/ada-url/ada/issues/617), the hashing technique to identify the protocol is unnecessary if the protocol string is predictable. By simply testing all six possible strings, starting from the most probable, it is likely that you can often get better performance in many practical cases.
It is a trade-off between best average or best-case performance and worst-case performance. A naive approach, in the worst case, may need to do six different string comparisons which could be potentially expensive. We made the choice to go with an option that is slightly less optimal in the case where we can predict, at compile time, the protocol, but has the benefit of having well understood worst-case performance. It is a …

Documenting hashing technique

---

.github/workflows/alpine.yml
.github/workflows/codeql.yml
.github/workflows/dependency-review.yml
.github/workflows/documentation.yml
.github/workflows/emscripten.yml
.github/workflows/lint_and_format_check.yml
.github/workflows/macos_install.yml
.github/workflows/release-script-tests.yml
.github/workflows/release_create.yml
.github/workflows/release_prepare.yml
.github/workflows/scorecard.yml
.github/workflows/ubuntu-release.yml
.github/workflows/ubuntu-s390x.yml
.github/workflows/ubuntu-sanitized.yml
.github/workflows/ubuntu-undef.yml
.github/workflows/ubuntu.yml
.github/workflows/ubuntu_install.yml
.github/workflows/ubuntu_old.yml
.github/workflows/ubuntu_pedantic.yml
.github/workflows/visual_studio.yml
.github/workflows/visual_studio_clang.yml
.github/workflows/wpt-updater.yml

This is required since Node.js 16 is now deprecated

chore: update github checkout workflow

---

cmake/clang-format.cmake

When consuming this library through fetch-content, cmake warns about missing python on my system.

prevent missing python warning when format feature not requested

---

src/helpers.cpp
src/unicode.cpp

@DenisYaroshevskiy suggested this optimization. He meant it for x64, but we do not currently support runtime dispatching nor do we expect our users to compile for a specific hardware, so we are limited to SSE2, which is not powerful enough for this trick.
On Apple M2, using `benchdata`. I repeat the benchmarks twice. 
Before:
```
BasicBench_AdaURL_href              24067654 ns     24065069 ns           29 GHz=3.50365 cycle/byte=9.4421 cycles/url=820.133 instructions/byte=40.1304 instructions/cycle=4.25016 instructions/ns=14.8911 instructions/url=3.4857k ns/url=234.079 speed=361.025M/s time/byte=2.76989ns time/url=240.591ns url/s=4.15644M/s
BasicBench_AdaURL_aggregator_href   16092015 ns     16089636 ns           44 GHz=3.50451 cycle/byte=6.29615 cycles/url=546.879 instructions/byte=28.065 …
```

optimize has_tabs_or_newline for NEON

---

benchmarks/CMakeLists.txt

The corrosion package does not appear to work properly under Windows. It breaks the build when enabling benchmarks.

Under Windows, Rust detection is broken and leads to a CMake error. Disabling it.

---

benchmarks/benchmark_template.cpp

Relates to: https://github.com/ada-url/ada/issues/377
```
Load Average: 0.06, 0.09, 0.09
ada spec: Ada follows whatwg/url
bad urls: ---------------------
ada---count of bad URLs       26
servo/url---count of bad URLs 26
whatwg---count of bad URLs    26
-------------------------------
bytes/URL: 86.859205
curl : OMITTED
input bytes: 8688092
number of URLs: 100025
performance counters: Enabled
rust version : 1.76.0
zuri : OMITTED
--------------------------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations UserCounters...
--------------------------------------------------------------------------------------------
BasicBench_AdaURL_href              30362199 ns     30356773 ns           23 GHz=4.29081 …
```

Add can_parse to benchmarks

---

src/url_aggregator.cpp
tests/basic_tests.cpp

Flagged by @anonrig in https://github.com/ada-url/ada/pull/657#issuecomment-2113591171

path setter bug

---

fuzz/parse.cc

Fuzzer now runs on all setters, getters and `parse<type>`
cc @CarlosEduR

improve parse fuzzer

---

src/ada_c.cpp

Simplifies C API.
- Replaces `NULL` with `nullptr`
- Replaces duplicate declarations with `auto`
- Fixes a clang-tidy warning for uninitialized variable.

fix: simplify c api

---

src/helpers.cpp
src/parser.cpp
src/unicode.cpp
src/url-getters.cpp
src/url-setters.cpp
src/url.cpp
src/url_aggregator.cpp
src/url_components.cpp

refactor: cleanup clang-tidy warnings

---

src/ada_c.cpp

Setting parameters of an object passed by value [do nothing even at GCC Og level](https://godbolt.org/z/M8exqe8oh)

refactor(ada_c/ada_free_owned_string): remove unused code

---

fuzz/parse.cc
fuzz/url.dict

Increases the fuzzing coverage

increase fuzzing coverage

---

.github/workflows/aarch64.yml
.github/workflows/cifuzz.yml

Fixes https://github.com/ada-url/ada/security/code-scanning/97

build: use fixed version for run-on-arch-action

---

fuzz/idna.cc
fuzz/parse.cc

Call ascii_has_upper_case from idna fuzzer

---

src/parser.cpp

This PR continues @CarlosEduR's work, and improves `ada::can_parse` by 20%
```
BasicBench_AdaURL_href                  2730 ns         2719 ns       256522 GHz=4.50694 cycle/byte=14.8762 cycles/url=1092.73 instructions/byte=70.5186 instructions/cycle=4.74035 instructions/ns=21.3645 instructions/url=5.17991k ns/url=242.455 speed=297.156M/s time/byte=3.36524ns time/url=247.192ns url/s=4.04544M/s
BasicBench_AdaURL_aggregator_href       1883 ns         1875 ns       373401 GHz=5.03164 cycle/byte=11.4146 cycles/url=838.455 instructions/byte=53.4653 instructions/cycle=4.68394 instructions/ns=23.5679 instructions/url=3.92727k ns/url=166.636 speed=430.991M/s time/byte=2.32023ns time/url=170.432ns url/s=5.86745M/s
BasicBench_AdaURL_CanParse              1476 ns         1470 ns       476278 …
```

perf: optimize `ada::can_parse` more

---

benchmarks/CMakeLists.txt
src/unicode.cpp

This seems to slightly reduce the instruction count for `url_aggregator`, but please run local benchmarks to verify
Before:
- ada_url -> instructions/url=2.55753k
- ada_url_aggregator -> instructions/url=2.76077k
After:
- ada_url -> instructions/url=2.55742k
- ada_url_aggregator -> instructions/url=2.76044k

perf: improve has_tabs_or_newline performance

---

fuzz/url_search_params.cc
include/ada/url_search_params-inl.h
include/ada/url_search_params.h
include/ada_c.h
src/ada_c.cpp
tests/ada_c.cpp

Adds a new API to reuse the existing std::vector.
Usage:
```c
TEST(ada_c, ada_search_params_reset) {
ada_url_search_params out;
std::string_view input = "a=b&c=d&c=e&f=g";
out = ada_parse_search_params(input.data(), input.size());
ASSERT_EQ(ada_search_params_size(out), 4);
std::string_view resetted_value = "a=b";
ada_search_params_reset(out, resetted_value.data(), resetted_value.size());
ASSERT_EQ(ada_search_params_size(out), 1);
ada_free_search_params(out);
SUCCEED();
}
```
Fixes https://github.com/ada-url/ada/issues/699

feat: add `url_search_params_reset` api

---

include/ada/url-inl.h
include/ada/url_aggregator-inl.h
tests/basic_tests.cpp

fixes https://github.com/ada-url/ada/issues/716

fix issue 716

---

.github/workflows/dependency-review.yml
.github/workflows/lint_and_format_check.yml
.github/workflows/macos_install.yml
.github/workflows/ubuntu-release.yml
.github/workflows/ubuntu-s390x.yml
.github/workflows/ubuntu-sanitized.yml
.github/workflows/ubuntu-undef.yml
.github/workflows/ubuntu.yml
.github/workflows/ubuntu_install.yml
.github/workflows/ubuntu_pedantic.yml
.github/workflows/visual_studio.yml
.github/workflows/wpt-updater.yml

Updates github workflow to reflect CPU count on each runner

update github workflows

---

include/ada/ada_idna.h
src/ada_idna.cpp

Updates idna code to `main` branch of the project

update ada::idna to c++20

---

src/unicode.cpp
src/url-setters.cpp
src/url.cpp
src/url_aggregator.cpp

It seems we forgot to check them using `constexpr`
```
BasicBench_AdaURL_url                202523 ns       201802 ns         3461 GHz=4.79069 cycle/byte=44.3605 cycles/url=1.07173k instructions/byte=111.316 instructions/cycle=2.50935 instructions/ns=12.0215 instructions/url=2.68935k ns/url=223.711 speed=102.001M/s time/byte=9.80384ns time/url=236.857ns url/s=4.22195M/s
BasicBench_AdaURL_url_aggregator     166170 ns       166133 ns         4221 GHz=4.79185 cycle/byte=36.7923 cycles/url=888.888 instructions/byte=113.701 instructions/cycle=3.09034 instructions/ns=14.8085 instructions/url=2.74697k ns/url=185.5 speed=123.901M/s time/byte=8.07096ns time/url=194.991ns url/s=5.12843M/s
```
```
BasicBench_AdaURL_url                194068 ns       194060 ns         3588 GHz=4.79139 …
```

check template arguments with constexpr

---

include/ada/common_defs.h
src/helpers.cpp
tests/basic_fuzzer.cpp

Mostly, we just remove unnecessary lines of code.

simplify endian handling

---

.github/workflows/aarch64.yml
benchmarks/wpt_bench.cpp
src/CMakeLists.txt

This modifies slightly one of our benchmark program so that we can narrowly benchmark URLs one by one if needed.

allows you to benchmark against 1 chosen URL.

---

include/ada/checkers.h
include/ada/common_defs.h
include/ada/unicode.h
src/checkers.cpp
src/unicode.cpp

Since we don't target for GCC8, let's remove `ada_constexpr`

remove ada_constexpr declaration

---

include/ada/log.h

The logging code predates folds. It is suitable for C++11, but we can do better now.
https://en.cppreference.com/w/cpp/language/fold

simplify logging

---

include/ada/url_aggregator-inl.h
include/ada/url_aggregator.h
src/parser.cpp

In our main parsing function, we repeatedly call set_host. This is a relatively expensive setter function.
It is only a wrapper around `set_host_or_hostname<false>`, but that function is not cheap...
```cpp
bool url_aggregator::set_host(const std::string_view input) {
return set_host_or_hostname<false>(input);
}
```
Let us look at it:
```cpp
template <bool override_hostname>
bool url_aggregator::set_host_or_hostname(const std::string_view input) {
ada_log("url_aggregator::set_host_or_hostname ", input);
ADA_ASSERT_TRUE(validate());
ADA_ASSERT_TRUE(!helpers::overlaps(input, buffer));
if (has_opaque_path) {
return false;
}
std::string previous_host(get_hostname());
uint32_t previous_port = components.port;
size_t host_end_pos = input.find('#');
std::string _host(input.data(), host_end_pos …
```

introduce a new method (set_host_to_base_host) to replace set_host when set_host is unnecessary

---

.github/workflows/aarch64.yml
.github/workflows/alpine.yml
.github/workflows/emscripten.yml
.github/workflows/macos_install.yml
.github/workflows/ubuntu-s390x.yml
.github/workflows/ubuntu-sanitized.yml
.github/workflows/ubuntu-undef.yml
.github/workflows/ubuntu.yml
.github/workflows/ubuntu_install.yml
.github/workflows/ubuntu_pedantic.yml
.github/workflows/visual_studio.yml
.github/workflows/visual_studio_clang.yml
CMakeLists.txt
cmake/ada-flags.cmake

This makes sure that, by default, doing `cmake -B build` does not trigger any network access. So tests and tools must be enabled by a specific flag.
If we make this change **we should document it**.
Alternative to https://github.com/ada-url/ada/pull/772

avoid network access by default

---

include/ada/common_defs.h
include/ada/unicode-inl.h

Small changes

---

cmake/CPM.cmake

Downgrading CPM might help with some CI issues.
Also, this includes the full CPM code, which avoids network access when building.

dowgrading CPM to 0.40.0 + including full version

---

README.md

Adds multiple clients to README.
A small thank you to @lnear-dev @bungle @alperencantez @TkTech @KusStar for their incredible libraries.
I also invite you to open a pull request to github.com/ada-url/website to add your names and libraries.

update readme and add clients

---

include/ada/url_search_params-inl.h

Let's use more C++20 functionality.

use more c++20 functions

---

benchmarks/CMakeLists.txt
benchmarks/competitors/servo-url/Cargo.lock
benchmarks/competitors/servo-url/Cargo.toml
benchmarks/competitors/servo-url/lib.rs

We are still the fastest URL parser on both RFC-3986 and WHATWG.
```
--------------------------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations UserCounters...
--------------------------------------------------------------------------------------------
BasicBench_AdaURL_href                  3411 ns         3404 ns       204433 speed=253.506M/s time/byte=3.94468ns time/url=378.251ns url/s=2.64375M/s
BasicBench_AdaURL_aggregator_href       2051 ns         2046 ns       338881 speed=421.819M/s time/byte=2.37068ns time/url=227.322ns url/s=4.39904M/s
BasicBench_AdaURL_CanParse              1431 ns         1425 ns       486000 speed=605.437M/s time/byte=1.6517ns time/url=158.38ns url/s=6.31394M/s …
```

update servo-url and fix detection

---

tests/wpt/toascii.json
tests/wpt/urlpattern-compare-test-data.json
tests/wpt/urlpatterntestdata.json
tests/wpt_tests.cpp
tools/update-wpt.sh

Updates `update-wpt.sh` script to include url pattern files

add urlpattern to update-wpt.sh

---

include/ada/parser.h
include/ada/url_pattern-inl.h
include/ada/url_pattern.h
src/implementation.cpp
src/parser.cpp
src/url_pattern.cpp

This is a minor fix for @anonrig's add-url-pattern. Mostly, we use a friend template instead of a friend function and we avoid unnecessary forward references by switching the include order.

minor fixes for add-url-pattern

---

tests/wpt_urlpattern_tests.cpp

simplify json logic

---

src/url_pattern.cpp

I don't think that the current regex code is safe?

guarding regex call

---

include/ada/url_pattern_helpers-inl.h
src/url_pattern_helpers.cpp
tests/wpt_urlpattern_tests.cpp

You have
```C++
if (parse_result.has_value()) {
```
where you need to have something like
```C++
if (parse_result.value().has_value()) {
```

I think that the test is in error

---

CMakeLists.txt
README.md

Fixes https://github.com/ada-url/ada/issues/825

removing git check

---

tests/wpt_urlpattern_tests.cpp

Adds missing test coverage for pattern::test() function

add urlpattern::test() tests

---

include/ada/url_components-inl.h
src/url.cpp

Addresses some of the issues in https://github.com/ada-url/ada/issues/842

address coverity issues

---

fuzz/idna.cc
fuzz/url_pattern.options

try to fix fuzzer

---

fuzz/url_pattern.cc

I am concerned that the fuzzer is a bit too crazy.

reduce the scope of the fuzzer

---

include/ada/url_pattern-inl.h
include/ada/url_pattern.h
include/ada/url_pattern_regex.h
src/url_pattern_regex.cpp

Realized that we didn't follow the spec on this one. There is a test case that checks if a group value is `undefined`. I'll follow up on the other PR once this lands.

make regex result accept optional string

---

include/ada/url_pattern.h
include/ada/url_pattern_helpers-inl.h
include/ada/url_pattern_helpers.h
src/url_pattern_helpers.cpp
tests/wpt_urlpattern_tests.cpp

Some all-case common words can be set by build systems, especially under Windows. For example, the symbol `STRICT` has a special meaning: https://learn.microsoft.com/en-us/windows/win32/winprog/enabling-strict
Should help get https://github.com/nodejs/node/pull/56452 building under Windows in Node.

avoiding macro clash

---

README.md
include/ada/url_pattern-inl.h
include/ada/url_pattern.h
include/ada/url_pattern_helpers.h
include/ada/url_pattern_init.h
include/ada/url_pattern_regex.h

let's hide several implementation detail before releasing a new version

hide implementation detail and update readme

---

.github/workflows/release_prepare.yml

clang++-14 is not available on `ubuntu-latest`

use ubuntu ubuntu-22.04-arm on release-prepare

---

.github/workflows/macos_install.yml
include/ada/url_pattern.h

let's test more macOS
the following error message only exist on macOS 13 and 14, but not on macOS 15 builds
```
/Users/runner/work/ada/ada/include/ada/parser-inl.h:117:16: error: 'protocol_component' is a private member of 'ada::url_pattern<ada::url_pattern_regex::std_regex_provider>'
url_pattern_.protocol_component = std::move(*protocol_component);
^
/Users/runner/work/ada/ada/include/ada/implementation-inl.h:21:18: note: in instantiation of function template specialization 'ada::parser::parse_url_pattern_impl<ada::url_pattern_regex::std_regex_provider>' requested here
return parser::parse_url_pattern_impl<regex_provider>(std::move(input),
^
/Users/runner/work/ada/ada/tests/wpt_urlpattern_tests.cpp:29:12: note: in instantiation of function template specialization …
```

add more macos versions to test

---

include/ada/url_search_params-inl.h
tests/url_search_params.cpp

In https://github.com/ada-url/ada/pull/861, @npaun reported an issue with how we sort in URLSearchParams.sort. A reasonable interpretation is that we should sort in UTF-16 code units. That is what this PR does. I am including @npaun's test case (although, using only ASCII characters to avoid issues).

fixing issue 861

---

tests/url_search_params.cpp

This PR adds the remaining test cases for url_search_params::sort taken from WPT (https://github.com/web-platform-tests/wpt/blob/master/url/urlsearchparams-sort.any.js). They're all passing.
I skipped the case involving "ﬃ&🌈" because it's in @lemire's fix PR #863.

Add remaining Web Platform Tests for url_search_params::sort

---

include/ada/url_pattern-inl.h
include/ada/url_pattern.h
include/ada/url_pattern_regex.h

Improves the performance of both happy path and bad path, and reduces unnecessary string copies.
PS: We need benchmarks for URLPattern, but the change is not controversial.

improve urlpattern::match() performance

---

.github/workflows/macos_install.yml

It seems the macOS-build workflow fails at the moment on main.

add fail-fast: false to macos install

---

include/ada/parser-inl.h
include/ada/url_pattern-inl.h
include/ada/url_pattern_helpers.h
include/ada/url_pattern_init.h
src/url_pattern.cpp
src/url_pattern_helpers.cpp

Small performance improvement by reducing string allocations and comparisons in URLPattern

reduce string allocations in urlpattern

---

include/ada/url_pattern_helpers-inl.h
include/ada/url_pattern_helpers.h

Adds const to several methods, and puts to_string method behind ADA_TESTING flag

add const qualifier to several methods

---

include/ada/url_pattern_helpers-inl.h
include/ada/url_pattern_helpers.h
src/url_pattern.cpp
src/url_pattern_helpers.cpp

Removes multiple string allocations and copies in url_pattern_init::process()

reduce string allocations in url_pattern_init::process

---

include/ada/url_pattern-inl.h
include/ada/url_pattern_helpers-inl.h
include/ada/url_pattern_helpers.h
src/url_pattern_helpers.cpp

further reduce unnecessary string copies

---

.github/workflows/ubuntu_pedantic.yml
include/ada/url_pattern_helpers-inl.h
tests/wpt_urlpattern_tests.cpp

Unblocks Node.js from updating

fix -Wextra related bugs

---

tools/cli/adaparse.cpp

On Windows, the equivalent of `/dev/nul` is `nul`. Using `/dev/nul` on Windows will cause the program to throw a runtime exception when the output parameter is not specified.

fix: resolve std::system_error in adaparse on Windows

---

README.md

Hello! The Zig bindings alperencantez provided don't seem to be up to date with the latest Ada changes. 
I have Zig bindings that are maintained and in use in my downstream projects, so hopefully it provides an improved interface for Zig developers wanting to use Ada.
Thanks.

Change zig bindings link

---

src/helpers.cpp
src/url_aggregator.cpp
tests/basic_tests.cpp

This fixes #935 
The code for fast path, assumed only 1 dot exists.

Fixing #935

---

src/checkers.cpp
src/parser.cpp
src/unicode.cpp
src/url.cpp
src/url_aggregator.cpp

using ranges

---

include/ada/encoding_type.h
src/implementation.cpp

feat: Optimize `to_string`

---

src/url.cpp
src/url_aggregator.cpp
tests/wpt/ada_extra_setters_tests.json

This change updates set_port so that when the input consists only of tab (\t), newline (\n), or carriage return characters, the port is left unchanged. Also adds these cases to ada_extra_setters_tests.json while waiting for their inclusion in WPT.
Refs: https://github.com/web-platform-tests/wpt/pull/53420

fix(url): handle tab/newline-only inputs in set_port

---

src/url.cpp
src/url_aggregator.cpp
tests/wpt/ada_extra_setters_tests.json

The current implementation incorrectly allows values like ":80" (empty host with port), resulting in `foo://:80/to`, while the spec requires failure if the host is missing. This update aligns behavior with the spec.
```js
const NodeURL = require("url").URL;
const WhatwgURL = require("whatwg-url").URL;
const newHost = ':80';
const url = new NodeURL("foo://path/to");  
url.host = newHost;
console.log(url.href); // Wrong: foo://:80/to
const url2 = new WhatwgURL("foo://path/to");
url2.host = newHost;
console.log(url2.href); // Correct: foo://path/to
```
Refs: https://url.spec.whatwg.org/#host-state
> If buffer is the empty string, host-missing validation error, return failure.
WPT tests for this case will be added in a follow-up PR.

fix(url): handle :port values in host setter

---

tests/wpt_urlpattern_tests.cpp

This PR fixes a test error with `ada_log` caused by calling a nonexistent `to_string` method on url_pattern. According to the WHATWG specification, `url_pattern` does not provide a `to_string` method. Instead of implementing a `to_string` method, I changed the logging output.
Steps to reproduce:
```sh
cmake -B build -DADA_TESTING=ON
cmake --build build 
ADA_LOGGING=1 ctest --output-on-failure --test-dir build
```
Outputs:
```sh
parse_result:
protocol: 'https'
username: 'user'
password: 'pass'
hostname: 'example.com'
port: '8080'
pathname: '/path'
search: '?query'
hash: '#fragment'
```
Refs:
+ https://github.com/ada-url/ada/blob/main/include/ada/url_pattern_init.h

fix(test): remove nonexistent url_pattern::to_string() call

---

include/ada/url_pattern_init.h

This PR adds a required operator`<<` overload for the `process_type` enum, which is necessary for logging with ada_log. If there is a more appropriate or recommended way to handle this, please let me know!
Steps to reproduce:
```sh
cmake -B build -DADA_TESTING=ON
cmake --build build 
ADA_LOGGING=1 ctest --output-on-failure --test-dir build
```

fix(logging): add missing process_type ostream operator<<

---

include/ada/common_defs.h
src/helpers.cpp
src/unicode.cpp

Binutils(2.41) and GCC(14.1.0) complete LSX and LASX support
More details: https://github.com/loongson/build-tools/wiki
After using LSX, the performance is improved by 5-10%.
Some reference documents for loongarch64 architecture LSX：
LoongArch SX Vector Intrinsics： https://gcc.gnu.org/onlinedocs/gcc/LoongArch-SX-Vector-Intrinsics.html
Unofficial LoongArch Intrinsics Guide： https://jia.je/unofficial-loongarch-intrinsics-guide/
Currently, it has passed all tests in LoongArch architecture 2k2000(only support LSX), 3C5000, 3A6000 environment
**LoongArch64 2K2000 machine benchmark test results**
```
main:
Loading /home/zhoumt/ada/build/_deps/url-dataset-src/out.txt
2025-07-10T09:46:19+08:00
Running ./benchmarks/benchdata
Run on (2 X 1400 MHz CPU s)
CPU Caches:
L1 Instruction 64 KiB (x2)
L1 …
```

LoongArch64: add lsx support

---

.clang-tidy

Quick follow-up to https://github.com/ada-url/ada/pull/981
Suppress clang-tidy's `clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling` check, which produces false positives for functions like `fprintf()`. Further, this check recommends adoption of C11 Annex K functions that are unavailable under many libc's (including glibc) and controversial amongst experts.
Apologies for not including this as part of https://github.com/ada-url/ada/pull/981. I only realized after merging that although this check does not currently generate false positives on the ada codebase, it would be confusing for contributors to have future PRs blocked because of innocent/innocuous use of functions like `fprintf()` and `memset()`.
For additional background:
- …

suppress `clang-tidy` warnings re: Annex K functions

---

cmake/CPM.cmake

Unfortunately, we have a hardcopy of CPM, so we need to do a large update.

updating CPM

---

.github/workflows/ubuntu-riscv64-rvv.yml
cmake/toolchains-dev/README.md
cmake/toolchains-dev/riscv64-rvv.cmake
include/ada/common_defs.h
src/helpers.cpp
src/unicode.cpp

This adds support for the RISC-V vector extension.
One the SpacemiT X60, I get speedups of 1.12x, 1.15x and 1.24x, for AdaURL_href, AdaURL_aggregator_href and AdaURL_CanParse respectively. This is in-line with, even above, the relative speedup from the SSE code paths when toggled on Zen1 (1.04x, 1.01x and 1.11x).
I decided to use LMUL=1 because URLs usually are on the smaller side.
There is a `#if`ed out codepath that implements `find_next_host_delimiter_special()` with a LUT, which was slower than the regular implementation on the X60, but I could see if being faster on future OoO hardware.
I didn't add runtime ISA detection yet, because I expect toolchains to move the default to RVA23 in the future. That would probably be better in a seperate PR anyways, as ada currently doesn't have …

add RVV support
